### PR TITLE
Suppress Gtk terminal junk

### PR DESCRIPTION
**Pull request by dagewa**
You know those annoying messages like this from the viewers?
```
Gtk-Message: 14:31:36.498: Failed to load module "atk-bridge"
Gtk-Message: 14:31:36.499: Failed to load module "canberra-gtk-module"
```

This change makes them go away. At least, it does for me.

### CODE REVIEW

**Comment by Baharis** [comment]
The "At least, it does for me" part intrigued me, so I checked out on this branch on my Perlmutter installation — which is otherwise a few weeks out of date. It seems the "canberra-gtk-module" warning is still there. Does it work out of the box for you, or should I do anything else?

**Comment by dagewa** [comment]
Apparently it only works with glib 2.50 or later, so maybe that's the issue?

**Comment by dagewa** [comment]
Well, that's what it says at https://docs.wxwidgets.org/trunk/classwx_app.html#a54432e69998e785a22838699ef8bf8f9, but that seems like nonsense as the current latest version is 2.37 (https://www.gnu.org/software/libc/). Maybe they mean 2.5.0. Anyway, according to `ldd --version`, I have 2.27.

**Comment by dagewa** [comment]
Oops, wrong library. glib version, not glibc version 🙄

**Comment by dagewa** [comment]
I just tried at Diamond and happily this does work there.

**Comment by dagewa** [comment]
@bkpoon I noticed this affects `cctbx.multiplicity_viewer` too. Possibly you want something like this in `wxtbx.app.CCTBXApp`?

**Comment by bkpoon** [comment]
Yeah, we can add it. Should it be in the constructor for the `CCTBXApp` class? We can add a keyword argument like `suppress_gtk_diagnostics` that defaults to `True` and runs that try/except block. And if someone needs to debug, they can   set that keyword to `False` in their code.

**Comment by dagewa** [comment]
Yeah, as it seems to work when called ahead of the constructor, then putting it first thing in the `__init__` makes sense. Apparently you can mask specific message types, but I didn't look into that. I think making it a binary on/off under keyword control sounds much simpler :+1:

**Comment by bkpoon** [comment]
I created the `gtk-error` branch in `cctbx_project`. @dagewa Can you test it? My default linux server is CentOS and it seems to have all the expected modules, so I don't get those error messages.

We can tweak the behavior. The keyword is `gtk_suppress_diagnostics` to match the function name, but we can change that as well.

And I agree that the binary choice is simplest.

**Comment by dagewa** [comment]
Yep, works perfectly for me, thanks!

**Comment by bkpoon** [comment]
I just committed the change, so it should be generally available now.

**Comment by dagewa** [comment]
Thanks! I updated the `CCTBXApp`s in DIALS to use the new mechanism.

**Pull request merged**
