### PR TITLE
Add a 'scaled' flag to the reflection table.

### PR DESCRIPTION
**Pull request by jbeilstenedmands**
Introduce a 'scaled' flag, which is set at the end of scaling to indicate which are the good scaled reflections (not excluded, not outliers etc). This is the inverse of the current 'bad_for_scaling' flag, which is unclear and prone to misuse, as indicated by the confusion in the discussion in #1268.

Ideally, the scaled flag will replace all uses of 'bad_for_scaling' outside scaling code - this has not been implemented yet, as it will require updating some of the regression test files (e.g. l_cysteine_4_sweeps_scaled). If we're happy with the proposed changes here, then once merged I can update the test files and implement further changes of bad_for_scaling to scaled in places such as `dials.util.filter_reflections`

### CODE REVIEW

**Comment by ndevenish** [comment]
I think we're ready to merge this when the conflicts are resolved

**Comment by ndevenish** [comment]
What's the relation between `scaled` and `bad_for_scaling`? It seems to set scaled as the exact opposite quite often, but I can't tell if there are scenarios where they diverge.

**Comment by ndevenish** [comment]
Also, needs a newsfragment (probably `.api`?)

**Comment by jbeilstenedmands** [comment]
@ndevenish you are correct, as in the PR description, I'm moving over to the scaled flag in general outside of internal scaling code, although keeping bad_for_scaling for convenience within scaling (at least for now). Newsfragment incoming.

**Comment by ndevenish** [comment]
D'oh, that's what I get for reading the code and not the description.

Is the long term idea to properly deprecate the bad_for_scaling?

**Pull request merged**
