### PR TITLE
Force multiprocessing to use fork in dials.find_spots_server

### LINKED ISSUE #1447: dials.find_spots_server does not start on Python 3.8 platform
Just tried to start this on my development build, freshly bootstrapped a couple days ago on a Python 3.8 platform:

```
Grey-Area fss :( $ dials.find_spots_server 
Thu Oct  8 06:33:01 2020 Serving 8 processes on port 1701
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/find_spots_server.py", line 337, in <module>
    main(params.nproc, params.port)
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/find_spots_server.py", line 320, in main
    proc.start()
  File "/Users/graeme/svn/cctbx/conda_base/python.app/Contents/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/graeme/svn/cctbx/conda_base/python.app/Contents/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/graeme/svn/cctbx/conda_base/python.app/Contents/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/graeme/svn/cctbx/conda_base/python.app/Contents/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/graeme/svn/cctbx/conda_base/python.app/Contents/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/graeme/svn/cctbx/conda_base/python.app/Contents/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/graeme/svn/cctbx/conda_base/python.app/Contents/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_thread.lock' object
```

Computer say nope

### PR DESCRIPTION
**Pull request by graeme-winter**
Fixes #1447

### CODE REVIEW

**Comment by ndevenish** [comment]
While I'd like to know how to get it to work under the new multiprocessing spawn method, this is fine to get it working. Do we want to limit the start method to python 3.8 on mac? e.g. `    if sys.hexversion >= 0x3080000 and sys.platform == "darwin":`, the same as the check to skip the tests

**Comment by Anthchirp** [comment]
If this does fix (or side-step) the issue then the skip line should be removed from the test

**Comment by ndevenish** [comment]
It does, but the test needs changing here also, and my refactoring in #1443 removes the need so happy to do it there. Or merge it first.

**Comment by graeme-winter** [comment]
Added platform check as suggested, did not remove skip from test as looks like @ndevenish  you have things in flight for this?

**Comment by ndevenish** [comment]
Okay, merged #1443 and removed the check here

**Pull request merged**
