### PR TITLE
Remove magic number in dials integrate

### PR DESCRIPTION
**Pull request by graeme-winter**
Include derivation to aid future reader

### CODE REVIEW

**Review by benjaminhwilliams — APPROVED** [review]
LGTM, thanks.

**Comment by graeme-winter** [comment]
Actually, hold the line. I have a small suspicion that the magic number is the wrong magic number (not by much) which I would like to check...

**Comment by graeme-winter** [comment]
Graeme's hit-list += `EPS = 1e-7`

**Comment by graeme-winter** [comment]
> tests/algorithms/profile_model/ellipsoid/test_model.py

I think I got all these

**Pull request merged**
