### PR TITLE
Sourceforge really is no more

### PR DESCRIPTION
**Pull request by graeme-winter**
User fed back that "haven't heard of sourceforge for like 8 years"

And correctly so, propose some updates

### CODE REVIEW

**Comment by dagewa** [comment]
The mailing list still works though, and or people without github accounts that provides an easier way to report issues. So unless we can replace dials-support@lists.sourceforge.net with some other address, my preference would be to keep that in the error messages.

**Comment by phyy-nx** [comment]
Jiscmail would be fine, but keeping [dials-support@lists.sourceforge.net](mailto:dials-support@lists.sourceforge.net) is also fine

**Comment by dagewa** [comment]
@phyy-nx I wanted to check, since funding situation is now different since this time last year, would you still be happy if we moved the support email address to jiscmail.ac.uk?

**Comment by dagewa** [comment]
TBH I see no problem keeping the sourceforge mailing list. It works and there are [not a huge number of free alternatives](https://opensource.stackexchange.com/questions/1470/free-mailing-list-provider-for-open-source-projects) for open source projects (note xia2 uses gmail though). In that case, this PR would just need fixing up to keep the sourceforge address in error messages.

**Comment by phyy-nx** [comment]
For now, let's keep it on sourceforge?  I'm interested in a larger conversation about user support spaces for DIALS, so I think even if the email should change, I'm not yet ready to say what it should change to.

**Review by phyy-nx — APPROVED** [review]
Approving since I have edits I need to do to add the DIALS R24

**Comment by phyy-nx** [comment]
I think the test failures here are unrelated, so merging.

**Pull request merged**
