### PR TITLE
Log the image template

### PR DESCRIPTION
**Pull request by dagewa**
WIP for #1662

This works for scans, but not for stills. Could somebody who works with stills please add in the appropriate code path? I don't know how to get a template out of an `ImageSet` and anyway I don't know how you want to report the possibly cherry-picked image numbers.

### CODE REVIEW

**Comment by dagewa** [comment]
Tagging @graeme-winter, @phyy-nx and @rjgildea as those who commented on #1662

**Comment by dagewa** [comment]
Tempted to merge this, because it is an improvement for users processing scans and doesn't change the behaviour for users processing stills. Any thoughts?

**Comment by dagewa** [comment]
Sigh. Implicit rebase when I did a `git pull` has left this all messy :-(

**Comment by phyy-nx** [comment]
Ok with me.  Sorry I haven't had a chance to work on it.

**Comment by dagewa** [comment]
Just to note, this is also relevant for #2072, though that request is also to put this information in spot-finding and integration logs, so this does not strictly close it.

@jbeilstenedmands I think you said you might look at this for stills? If not soon, I'd be keen to merge this.

**Pull request merged**
