### PR TITLE
bootstrap updates

### PR DESCRIPTION
**Pull request by Anthchirp**
* Refactor bootstrap script to make the control flow more obvious
* Rewrite the source checkout logic to allow more complex setups
* By default, check out the `master` branch from `dials/cctbx` rather than from `cctbx_project/cctbx` with the local branch name `stable`.
  * [This branch follows the `cctbx_project/cctbx` master branch, and automatically advances whenever the cctbx CI tests pass](https://github.com/cctbx/cctbx_project/commit/15676b42fc80fbe17922df64882c2c7af44b2932). Therefore the checked out copy will not be known unstable.
  * A local pre-commit is set up to reject local commits to the `stable` branch. All other branches will behave normally.
  * One can at any time `git checkout master` to get access to the regular `cctbx_project` `master` branch, and similarly check out any other branch from the `cctbx_project/cctbx` remote. Branches from the `dials/cctbx` remote are also available.
* ~PR also includes the update numpy 1.16 ➡️ 1.17 (half-way move for #1289)~

### CODE REVIEW

**Comment by graeme-winter** [comment]
`dials/cctbx as stable` - sounds sensible - the only side-effect I can see is that e.g. changes to `cctbx.xfel` would not propagate if there are (to pick a random example) failing tests in `mmtbx`

Evidently this would only affect those using the DIALS bootstrap, not the old `cctbx_project` one, so the main way anyone would notice this is that (in the circumstances above) nightly builds would not contain any `cctbx_project` fixes until other bugs are fixed. I guess this reflects the issue with keeping everything in one repo rather than a collection of repos so 🤷‍♂️  not much you can do about that...

**Comment by graeme-winter** [comment]
To be clear: I'm happy with this as it will make development builds much more stable!

**Comment by Anthchirp** [comment]
If there are no concerns I'll merge this over the weekend together with #1289.

**Comment by ndevenish** [comment]
I'd prefer dependency updates be separated

**Pull request merged**
