### PR TITLE
Thaumatin 2021 tutorial

### LINKED ISSUE #1737: Update DIALS "processing in detail" to 2021 Eiger data
Would seem sensible to bring this somewhat up to date

### PR DESCRIPTION
**Pull request by graeme-winter**
Work in progress but putting this here so people can see what I am up to and maybe even make helpful suggestions. This will be more lightweight / less comprehensive than the previous version. 

This will fix #1737

### CODE REVIEW

**Comment by rjgildea** [comment]
Just to point out we do have a slightly more up-to-date [tutorial using SARS-CoV-2 MPro data](https://dials.github.io/documentation/tutorials/mpro_x0692.html) from I04-1 (although obviously this is from a recently-retired PILATUS detector rather than an EIGER). I would recommend adding any new tutorial to the [`dials.generate_tutorial_text`](https://github.com/dials/dials/blob/main/command_line/generate_tutorial_text.py) command to ensure than the tutorial remains functional and the output current.

**Comment by graeme-winter** [comment]
Totally valid suggestion which is beyond my reach and unlikely given my current deadline of resolving this by next week!

Also wanted to have a tutorial for well measured data...

**Comment by rjgildea** [comment]
It shouldn't be _too_ difficult - see https://github.com/dials/dials/commit/f69fc319a4304ff54ed88805adb4af81b414a2bd for how it was done for the MPro tutorial. Should mostly be a copy/pasta job, right? :)

**Comment by graeme-winter** [comment]
Closing for the moment - I think this may need to be done _properly_ so I will come up with something immediate for the needs for next week and revisit

**Pull request closed without merging**
