### PR TITLE
a DIALS bootstrap script

### PR DESCRIPTION
**Pull request by Anthchirp**
The DIALS bootstrap will only create Python3+Conda environments, that are updateable post-bootstrap. Python 2.7 and non-conda environments are not supported. Rollout is planned for February 2020, at which point xia2/DIALS developers are expected to move over to a Python 3 environment in preparation for Python 2.7 retirement.

### CODE REVIEW

**Comment by Anthchirp** [comment]
First iteration of a DIALS bootstrap script.
```
python bootstrap.py
```
is equivalent to
```
python bootstrap.py --builder=dials hot update base build --python3 --use-conda --nproc=X
```

Major differences:
* Only creates conda environments
* Only supports DIALS builder
* Only supports Python 3 environments
* `hot` stage is gone, all source downloads happen in `update` step
* Automatically uses all cores

**Comment by graeme-winter** [comment]
Time for some testing?

**Comment by Anthchirp** [comment]
yes, this is ready for testing.

**Comment by graeme-winter** [comment]
Wilco, acting on this now

**Comment by graeme-winter** [comment]
Worked for me 🙂

**Comment by rjgildea** [comment]
Seconded, worked for me on Mac (Mojave) and Linux (RHEL7) 👍

**Comment by Anthchirp** [comment]
Will address further feature requests on an ongoing basis.

**Pull request merged**
