### PR TITLE
Remove walrus operators

### PR DESCRIPTION
**Pull request by dwpaley**
This week we experienced a terrible dependency car crash which was summarized as: dxtbx doesn't support c++14, so we need boost 1.74, so we need psana 4.0.47, so we need python 3.7. (see: https://github.com/dials/dials/issues/2291) The details are not important for this PR, but they illustrate that despite all best intentions, in 2022 there is still enough py37 in the world that we might occasionally really wish that we still supported it. So we := myself, @phyy-nx, @irisdyoung are asking if we can refrain from using walrus operators for a bit longer as a favor. It seems to be the only non-py37 feature that has actually made it into the codebase (or at least the most prominent).

Co-authored-by: Aaron Brewster <asbrewster@lbl.gov>
Co-authored-by: Iris Young <idyoung@gmail.com>

### CODE REVIEW

**Comment by ndevenish** [comment]
Additionally, how do I enable C++14 for a cctbx bootstrap? `cctbx_project/libtbx/configure.py` still only appears to have an `--enable_cxx11` flag.

**Comment by phyy-nx** [comment]
We see errors like this from bootstrap builds (dials or cctbx bootstrap):

```
In file included from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/comparable_distance/interface.hpp:24,
                 from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/index/rtree.hpp:32,
                 from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/within/multi_point.hpp:34,
                 from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/within/implementation.hpp:30,
                 from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/covered_by/implementation.hpp:25,
                 from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/covered_by.hpp:24,
                 from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/buffer/buffered_piece_collection.hpp:32,
                 from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/buffer/buffer_inserter.hpp:29,
                 from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/buffer.hpp:41,
                 from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/geometry.hpp:66,
                 from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry.hpp:17,
                 from /dev/shm/aaron/tmpdialsbuild/modules/dxtbx/src/dxtbx/masking/goniometer_shadow_masking.h:6,
                 from /dev/shm/aaron/tmpdialsbuild/modules/dxtbx/src/dxtbx/imageset.h:29,
                 from /dev/shm/aaron/tmpdialsbuild/modules/dxtbx/src/dxtbx/boost_python/imageset_ext.cc:9:
/dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/distance/interface.hpp: At global scope:
/dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/distance/interface.hpp:67:19: error: 'apply' function uses 'auto' type specifier without trailing return type
   67 |     static inline auto apply(Geometry1 const& g1, Geometry2 const& g2,
      |                   ^~~~
/dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/distance/interface.hpp:67:19: note: deduced return type only available with '-std=c++14' or '-std=gnu++14'
```

**Comment by phyy-nx** [comment]
There is no enable_cpp14 flag for the libtbx SConscript yet, but it's being worked on soon.  It's probably a stopper for #2291.

**Comment by graeme-winter** [comment]
> There is no enable_cpp14 flag for the libtbx SConscript yet, but it's being worked on soon. It's probably a stopper for #2291.

I suspect that _this_ is at the root of the problem as C++14 seems very well supported for a long time in most of the usual compilers. However I also know the headache that `scons` causes.

Discussion topic: move away from `scons`? ISTR we already use `cmake` for the conda package builds. I will make an issue.

**Comment by graeme-winter** [comment]
Re: the actual PR: I will note that it has been discussed extensively and that the use of walrus operators is consistent with our previously agreed language support schedule: I would very much prefer that we follow through and actually drop support for unsupported  platforms (since we have an explicitly LTS branch for the 3.8 series which _does_ support Python 3.7 for PHENIX and CCP4)

That said, _these_ changes are minor and reasonable so I do not object to merging this PR on the following understaning - 

 - this _does not_ prejudge the inclusion of using non 3.7-compatible language features in `main`
 - we have a serious conversation about getting rid of `scons` in the near term

The former of these means that there is a small chance of another walrus operator appearing sometime, but again if you have a worknig 3.7 environment then I guess you would spot it and could rewrite as you have here. 

Why am I making a fuss? I DO NOT WANT TO GET TRAPPED IN THE OBSOLETE PYTHON TAR PIT. We got trapped in there with Python 2.7 for a long time and it was a huge commitment and body of work to get out. Every PR like this is saying "tar pit this way" and I feel it is my job to make sure we don't go there again 🙂

I'm also sympathetic to the fact that you have other dependencies which are holding you back, and beam times to deal with, so this is a tricky path to walk...

**Comment by ndevenish** [comment]
> We see errors like this from bootstrap builds (dials or cctbx bootstrap):
> 
> ```
> In file included from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/comparable_distance/interface.hpp:24,
>                  from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/index/rtree.hpp:32,
>                  from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/within/multi_point.hpp:34,
>                  from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/within/implementation.hpp:30,
>                  from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/covered_by/implementation.hpp:25,
>                  from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/covered_by.hpp:24,
>                  from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/buffer/buffered_piece_collection.hpp:32,
>                  from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/buffer/buffer_inserter.hpp:29,
>                  from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/buffer.hpp:41,
>                  from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/geometry.hpp:66,
>                  from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry.hpp:17,
>                  from /dev/shm/aaron/tmpdialsbuild/modules/dxtbx/src/dxtbx/masking/goniometer_shadow_masking.h:6,
>                  from /dev/shm/aaron/tmpdialsbuild/modules/dxtbx/src/dxtbx/imageset.h:29,
>                  from /dev/shm/aaron/tmpdialsbuild/modules/dxtbx/src/dxtbx/boost_python/imageset_ext.cc:9:
> /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/distance/interface.hpp: At global scope:
> /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/distance/interface.hpp:67:19: error: 'apply' function uses 'auto' type specifier without trailing return type
>    67 |     static inline auto apply(Geometry1 const& g1, Geometry2 const& g2,
>       |                   ^~~~
> /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/distance/interface.hpp:67:19: note: deduced return type only available with '-std=c++14' or '-std=gnu++14'
> ```

This isn’t dxtbx being incompatible with C++ 14. This is boost being incompatible with C++11, which the tbx build system is explicitly requesting.

**Comment by graeme-winter** [comment]
> > We see errors like this from bootstrap builds (dials or cctbx bootstrap):
> > ```
> > In file included from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/comparable_distance/interface.hpp:24,
> >                  from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/index/rtree.hpp:32,
> >                  from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/within/multi_point.hpp:34,
> >                  from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/within/implementation.hpp:30,
> >                  from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/covered_by/implementation.hpp:25,
> >                  from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/covered_by.hpp:24,
> >                  from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/buffer/buffered_piece_collection.hpp:32,
> >                  from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/buffer/buffer_inserter.hpp:29,
> >                  from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/buffer.hpp:41,
> >                  from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/geometry.hpp:66,
> >                  from /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry.hpp:17,
> >                  from /dev/shm/aaron/tmpdialsbuild/modules/dxtbx/src/dxtbx/masking/goniometer_shadow_masking.h:6,
> >                  from /dev/shm/aaron/tmpdialsbuild/modules/dxtbx/src/dxtbx/imageset.h:29,
> >                  from /dev/shm/aaron/tmpdialsbuild/modules/dxtbx/src/dxtbx/boost_python/imageset_ext.cc:9:
> > /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/distance/interface.hpp: At global scope:
> > /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/distance/interface.hpp:67:19: error: 'apply' function uses 'auto' type specifier without trailing return type
> >    67 |     static inline auto apply(Geometry1 const& g1, Geometry2 const& g2,
> >       |                   ^~~~
> > /dev/shm/aaron/tmpdialsbuild/build/../conda_base/include/boost/geometry/algorithms/detail/distance/interface.hpp:67:19: note: deduced return type only available with '-std=c++14' or '-std=gnu++14'
> > ```
> 
> This isn’t dxtbx being incompatible with C++ 14. This is boost being incompatible with C++11, which the tbx build system is explicitly requesting.

OK, it must be noted

```
./cctbx_project/libtbx/SConscript:        libtbx.env.build_options.env_cxxflags.replace('c++14', 'c++11').replace('c++17', 'c++11')
./cctbx_project/libtbx/SConscript:        libtbx.env.build_options.env_cppflags.replace('c++14', 'c++11').replace('c++17', 'c++11')
```

suggests that we are _going out of our way to be incompatible_ with C++14 🙄

**Comment by dwpaley** [comment]
@graeme-winter Understand and agree with the desire to avoid a backwards-compatibility tarpit. This PR comes from the observations that (1) *at this moment* in the codebase there's essentially zero cost to keeping the syntax py37-compatible, and (2) It would be a valuable insurance policy for situations like this one.

FWIW, this is the crux of the problems this week:
```
dwpaley@dials:~
$ conda search psana -c lcls-i |tail -30
psana                         4.0.36  py39he2d4907_0  lcls-i
psana                         4.0.37  py27h5df8c28_0  lcls-i
psana                         4.0.37  py37h08fdcc3_1  lcls-i
psana                         4.0.38  py27h5df8c28_0  lcls-i
psana                         4.0.38  py37h08fdcc3_1  lcls-i
psana                         4.0.38  py37h08fdcc3_2  lcls-i
psana                         4.0.38  py38h4003512_1  lcls-i
psana                         4.0.38  py38h4003512_2  lcls-i
psana                         4.0.38  py39hb310ee0_1  lcls-i
psana                         4.0.38  py39hb310ee0_2  lcls-i
psana                         4.0.40  py27hf484d3e_0  lcls-i
psana                         4.0.40  py37ha721117_0  lcls-i
psana                         4.0.41  py27hf484d3e_0  lcls-i
psana                         4.0.41  py37ha721117_0  lcls-i
psana                         4.0.42  py27hf484d3e_0  lcls-i
psana                         4.0.42  py37ha721117_0  lcls-i
psana                         4.0.43  py27hf484d3e_0  lcls-i
psana                         4.0.43  py37ha721117_0  lcls-i
psana                         4.0.44  py27hf484d3e_0  lcls-i
psana                         4.0.44  py37ha721117_0  lcls-i
psana                         4.0.45  py27he01ca76_2  lcls-i
psana                         4.0.45  py27hf484d3e_0  lcls-i
psana                         4.0.45  py27hf484d3e_1  lcls-i
psana                         4.0.45  py37h9ae6cb7_2  lcls-i
psana                         4.0.45  py37ha721117_0  lcls-i
psana                         4.0.45  py37ha721117_1  lcls-i
psana                         4.0.46  py37h1fc9f46_0  lcls-i
psana                         4.0.46  py37h1fc9f46_1  lcls-i
psana                         4.0.47  py37h9ae6cb7_0  lcls-i
psana                         4.0.48  py39he10e754_0  lcls-i
```

4.0.38 is too old. 4.0.39-47 were only packaged for py27 and py37. 4.0.48 requires boost 1.78 and therefore also c++14. 

There are lots of alternatives that would also fix this, as demonstrated by the c++ standards and scons/cmake discussion above, but dewalrusing gives us some time to resolve those.

**Comment by graeme-winter** [comment]
@dwpaley as mentioned above I have sympathy for your plight, and I am happy for the walrus rehoming mission. Just wanted to state for record that this is not offering long term obsolete Python support 😉

Think we all good here

**Comment by dwpaley** [comment]
Thanks and duly noted :)

**Comment by ndevenish** [comment]
It't not alternatives though - your entire justification for this was that "dxtbx isn't compatible with C++14". This is not true, it's purely a function of libtbx that it breaks, not dxtbx. Plus, we kept the 3.8 LTS branch _specifically at your request, specifically for things like this_.

3.7 has been dropped for nearly a year now, I wouldn't bet that there isn't some behaviour coded against 3.8 libraries that can't be picked up in a purely syntax scan.

**Comment by dwpaley** [comment]
> your entire justification for this was that "dxtbx isn't compatible with C++14"

I was rushing to write this PR, that part of the premise was very underexamined and I apologize that it started the build systems discussion on the wrong note! These changes were the thing that empirically proved to keep our build working during live processing. The correct phrasing would have been simply: We can't currently use C++14 without doing a deeper dive.

**Comment by ndevenish** [comment]
I'd suggest asking the psana team to make a release with the old boost libraries.

**Comment by ndevenish** [comment]
It's also worth knowing that you can do `--branch dxtbx@branchname` with the dials bootstrap and it'll pull a specific named branch instead of main.

**Pull request merged**
