### PR TITLE
Be more permissive in profile fitting

### PR DESCRIPTION
**Pull request by rjgildea**
- Fit profiles to reflections with invalid pixels: Profile fitting can handle masked pixels, so no obvious reason to exclude all reflections with masked from profile fitting.
- Remove checks on bbox limits: this dramatically increases the number of profile-integrated reflections for multi-panel detectors

See #1291, #1294 and #1295

### CODE REVIEW

**Comment by rjgildea** [comment]
Testing on the x4wide data set with the help of https://github.com/cctbx/dxtbx/pull/177:
```
$ dials.import $(dials.data get -q x4wide)/*.cbf [multi_panel=True]
$ dials.find_spots imported.expt nproc=8
$ dials.index imported.expt strong.refl space_group=P41212
$ dials.refine indexed.{expt,refl}
$ dials.integrate refined.{expt,refl}
$ dials.scale integrated.{expt,refl} output.unmerged_mtz=scaled_unmerged.mtz output.merged_mtz=scaled.mtz
```
For `multi_panel=False` + master:
```
$ grep "Summary for experiment 0" -A 23 dials.integrate.log 
         Summary for experiment 0
        +---------------------------------------+-----------+---------+--------+
        | Item                                  |   Overall |     Low |   High |
        |---------------------------------------+-----------+---------+--------|
        | dmin                                  |      1.01 |    2.75 |   1.01 |
        | dmax                                  |     42.39 |   42.39 |   1.03 |
        | number fully recorded                 |  91832    | 6551    | 154    |
        | number partially recorded             |  13526    | 1100    |  13    |
        | number with invalid background pixels |  37567    | 1817    | 149    |
        | number with invalid foreground pixels |  19781    | 1089    |  83    |
        | number with overloaded pixels         |      0    |    0    |   0    |
        | number in powder rings                |      0    |    0    |   0    |
        | number processed with summation       |  85000    | 6505    |  84    |
        | number processed with profile fitting |  79978    | 6216    |  17    |
        | number failed in background modelling |      0    |    0    |   0    |
        | number failed in summation            |  19781    | 1089    |  83    |
        | number failed in profile fitting      |  24803    | 1378    | 150    |
        | ibg                                   |      2.84 |    8.52 |   0.52 |
        | i/sigi (summation)                    |      9.35 |   66.88 |  -0.26 |
        | i/sigi (profile fitting)              |     10.05 |   72.95 |   0    |
        | cc prf                                |      0.92 |    0.83 |   0.9  |
        | cc_pearson sum/prf                    |      0.99 |    0.99 |   0.46 |
        | cc_spearman sum/prf                   |      0.9  |    0.99 |   0.46 |
        +---------------------------------------+-----------+---------+--------+
```
For `multi_panel=False` + PR:
```
$ grep "Summary for experiment 0" -A 23 dials.integrate.log 
         Summary for experiment 0
        +---------------------------------------+-----------+---------+--------+
        | Item                                  |   Overall |     Low |   High |
        |---------------------------------------+-----------+---------+--------|
        | dmin                                  |      1.01 |    2.75 |   1.01 |
        | dmax                                  |     42.39 |   42.39 |   1.03 |
        | number fully recorded                 |  91832    | 6551    | 154    |
        | number partially recorded             |  13526    | 1100    |  13    |
        | number with invalid background pixels |  37567    | 1817    | 149    |
        | number with invalid foreground pixels |  19781    | 1089    |  83    |
        | number with overloaded pixels         |      0    |    0    |   0    |
        | number in powder rings                |      0    |    0    |   0    |
        | number processed with summation       |  85000    | 6505    |  84    |
        | number processed with profile fitting |  99918    | 7257    | 106    |
        | number failed in background modelling |      0    |    0    |   0    |
        | number failed in summation            |  19781    | 1089    |  83    |
        | number failed in profile fitting      |   4863    |  337    |  61    |
        | ibg                                   |      2.8  |    8.5  |   0.52 |
        | i/sigi (summation)                    |      9.35 |   66.88 |  -0.26 |
        | i/sigi (profile fitting)              |      8.71 |   67.42 |  -0.05 |
        | cc prf                                |      0.91 |    0.81 |   0.91 |
        | cc_pearson sum/prf                    |      0.99 |    0.99 |   0.51 |
        | cc_spearman sum/prf                   |      0.9  |    0.99 |   0.47 |
        +---------------------------------------+-----------+---------+--------+
```
For `multi_panel=True` + master:
```
$ grep "Summary for experiment 0" -A 23 dials.integrate.log 
         Summary for experiment 0
        +---------------------------------------+-----------+---------+--------+
        | Item                                  |   Overall |     Low |   High |
        |---------------------------------------+-----------+---------+--------|
        | dmin                                  |      1.02 |    2.76 |   1.02 |
        | dmax                                  |     42.67 |   42.67 |   1.03 |
        | number fully recorded                 |  84672    | 6090    | 137    |
        | number partially recorded             |  12541    |  956    |   8    |
        | number with invalid background pixels |  31364    | 1299    | 134    |
        | number with invalid foreground pixels |  12126    |  518    |  80    |
        | number with overloaded pixels         |      0    |    0    |   0    |
        | number in powder rings                |      0    |    0    |   0    |
        | number processed with summation       |  84484    | 6509    |  65    |
        | number processed with profile fitting |  66027    | 5497    |  11    |
        | number failed in background modelling |      0    |    0    |   0    |
        | number failed in summation            |  12126    |  518    |  80    |
        | number failed in profile fitting      |  30583    | 1530    | 134    |
        | ibg                                   |      2.84 |    8.47 |   0.51 |
        | i/sigi (summation)                    |      9.1  |   65.61 |  -0.46 |
        | i/sigi (profile fitting)              |     10.19 |   73.77 |  -0.17 |
        | cc prf                                |      0.92 |    0.82 |   0.91 |
        | cc_pearson sum/prf                    |      0.98 |    0.99 |   0.58 |
        | cc_spearman sum/prf                   |      0.89 |    0.99 |   0.62 |
        +---------------------------------------+-----------+---------+--------+
```
For `multi_panel=False` + PR:
```
$ grep "Summary for experiment 0" -A 23 dials.integrate.log 
         Summary for experiment 0
        +---------------------------------------+-----------+---------+--------+
        | Item                                  |   Overall |     Low |   High |
        |---------------------------------------+-----------+---------+--------|
        | dmin                                  |      1.02 |    2.76 |   1.02 |
        | dmax                                  |     42.67 |   42.67 |   1.03 |
        | number fully recorded                 |  84672    | 6090    | 137    |
        | number partially recorded             |  12541    |  956    |   8    |
        | number with invalid background pixels |  31364    | 1299    | 134    |
        | number with invalid foreground pixels |  12126    |  518    |  80    |
        | number with overloaded pixels         |      0    |    0    |   0    |
        | number in powder rings                |      0    |    0    |   0    |
        | number processed with summation       |  84484    | 6509    |  65    |
        | number processed with profile fitting |  89041    | 6596    |  77    |
        | number failed in background modelling |      0    |    0    |   0    |
        | number failed in summation            |  12126    |  518    |  80    |
        | number failed in profile fitting      |   7569    |  431    |  68    |
        | ibg                                   |      2.79 |    8.46 |   0.52 |
        | i/sigi (summation)                    |      9.1  |   65.61 |  -0.46 |
        | i/sigi (profile fitting)              |      9.19 |   73.07 |  -0.09 |
        | cc prf                                |      0.92 |    0.82 |   0.92 |
        | cc_pearson sum/prf                    |      0.98 |    0.99 |   0.33 |
        | cc_spearman sum/prf                   |      0.88 |    0.99 |   0.24 |
        +---------------------------------------+-----------+---------+--------+
```

I.e. for `multi_panel=False`, there is an increase from 79978 to 99918 profile-fitted reflections, and for `multi_panel=True`, there is an increase from 66027 to 89041 profile-fitted reflections.

**Comment by rjgildea** [comment]
Comparing the locations of the failed-in-profile-fitting reflections, obtained by `dials.filter_reflections integrated.refl flag_expression="failed_during_profile_fitting"`
For `multi_panel=False` + master:
Screenshot 2020-06-09 at 11 45 38
For `multi_panel=False` + PR:
Screenshot 2020-06-09 at 11 45 48
For `multi_panel=True` + master:
Screenshot 2020-06-09 at 11 48 34
For `multi_panel=True` + PR:
Screenshot 2020-06-09 at 11 48 56

**Comment by dagewa** [comment]
@jmp1985 it would be great to see your comments on this PR. It fixes serious problems with multi-panel integration, but are there any strong reasons why the mask and bbox limitations were there in the first place?

**Comment by jmp1985** [comment]
Hi Sorry for taking a while to reply to this. 

I'm trying to remember why I was so conservative about this. I think the main reason I wanted to avoid doing the profile fitting for reflections with invalid pixels is because the way in which the default transformation to reciprocal space works. For example, a pixel has it's intensity shared with a number of grid points in reciprocal space so if some pixels are masked then some grid points might have lower intensity than expected. I don't think there is a check to mask out reciprocal space grid points if this is the case so it may be that profile fitted intensities of these reflections may be biased. It may be worth testing whether this is the case. However, if the benefit of having estimates for these reflections outweighs the potential pitfalls then it is obviously worth doing!

**Comment by rjgildea** [comment]
Thanks for the feedback @jmp1985. Do you have any thoughts on how best to check for bias in the profile-fitted intensities?

**Comment by jmp1985** [comment]
@rjgildea I guess the best way to do this would be to simulate some reflection profiles and put them through the profile fitting algorithm.... perhaps you could modify one of the tests to do this. 

1. Generate a set of reflections with invalid pixels, the same true intensity and Poisson distributed pixel values.
2. Estimate the intensity of each reflection
3. Plot a histogram of (estimated - known) intensity and see if there is a consistent bias.

**Comment by ndevenish** [comment]
Needs a `newsfragment`

**Comment by rjgildea** [comment]
@jmp1985 I had a go at what I think you are suggesting (using 5 masked pixels per 9x9x9 shoebox, which is probably a little bit extreme). I think there is _some_ bias towards an underestimation of the intensity, although I'm not sure it's enough to prevent this change being merged, however it's could be something worth looking into in future:

```
import matplotlib.pyplot as plt
import random

from dials.algorithms.integration.fit import ProfileFitter
from dials.array_family import flex
from dials.test.algorithms.integration.profile.test_profile_fitting import (
    gaussian, add_poisson_noise
)

true_intensities = flex.double()
estimated_intensities = flex.double()

# Create profile
n = 9
p = gaussian((n, n, n), 1, (4, 4, 4), (2, 2, 2))
s = flex.sum(p)
p = p / s

for i in range(10000):
    # Copy profile
    c = add_poisson_noise(100 * p)
    b = flex.double(flex.grid(n, n, n), 0)
    m = flex.bool(flex.grid(n, n, n), True)
    for j in range(5):
        m[random.randint(0, n-1), random.randint(0, n-1), random.randint(0, n-1)] = False

    # Fit
    fit = ProfileFitter(c, b, m, p)
    intensity = fit.intensity()
    V = fit.variance()
    assert fit.niter() < fit.maxiter()

    true_intensities.append(flex.sum(c))
    estimated_intensities.append(fit.intensity()[0])

plt.scatter(true_intensities, estimated_intensities, s=10, alpha=0.3)
plt.plot(plt.xlim(), plt.xlim(), c="black")
plt.axes().set_aspect("equal")
plt.xlabel("True intensity")
plt.ylabel("Estimated intensity")
plt.show()

plt.hist(estimated_intensities - true_intensities)
plt.xlabel("estimated - true")
plt.ylabel("Frequency")
plt.show()
```
1297_scatter
1297_hist

**Comment by ndevenish** [comment]
Have considered this for 3.2 release but seems there are some outstanding questions about how whether it makes statistics worse in some cases, so leaving for now.

**Pull request merged**
