### PR TITLE
Override sigma b multiplier

### PR DESCRIPTION
**Pull request by graeme-winter**
Default is 2.0, which makes for large bounding boxes for background calculations - leaving this in place for still data. This pull request changes the default for rotation data to 1.0, which should substantially reduce the memory footprint but may have an impact on data quality. 

N.B. there is is no equivalent for sigma_m.

Will significantly help fixing https://github.com/dials/dials/issues/659

### CODE REVIEW

**Comment by graeme-winter** [comment]
First cut this seems to correspond to a factor of 4 reduction in memory use, which is helpful.

If this works out I will make this into a parameter, though this seems to be non-trivial (it passes through many many onion layers)

**Comment by graeme-winter** [comment]
Tests pass for me 🙂

**Comment by dagewa** [comment]
Can we run a few datasets to look at the effect on data quality?

**Comment by graeme-winter** [comment]
Of course

The default behaviour (i.e. no parameter) is that nothing changes - if you change the parameter the outcome will change obviously. Are you asking for this to be part of the review process to assess the impact of the change if you change the parameter value?

**Comment by dagewa** [comment]
No sorry, I hadn't twigged that defaults haven't changed

**Comment by graeme-winter** [comment]
The default was previously hard coded somewhere in the bottom of `dials.integrate` - I have just moved this up (though the default parameter still exists, as I don't want to change API) 

Still would appreciate someone eyeballing the changes

**Comment by graeme-winter** [comment]
@phyy-nx please could you confirm that this makes no difference to your processing. In principle the additional parameter could help in come cases, but that is maybe out of context

**Pull request merged**
