### PR TITLE
Update isort to fix pre-commit checks

### PR DESCRIPTION
**Pull request by snnbotchway**

### CODE REVIEW

**Comment by dagewa** [comment]
Thanks! I confirm this fixes #2324 for me. I'll leave it to @ndevenish to approve, in case the version change has other consequences of which I'm not aware.

**Comment by snnbotchway** [comment]
Alright, sure

**Comment by ndevenish** [comment]
Cause appears to be https://github.com/PyCQA/isort/pull/2078

**Comment by ndevenish** [comment]
Thanks!

**Comment by snnbotchway** [comment]
You're welcome

**Pull request merged**
