### PR TITLE
dials.find_spots: fix counting in histogram output

### LINKED ISSUE #1826: dials.find_spots: text output is misleading
Imported 8 data sets, performed spot finding, found this in the output:

```

Histogram of per-image spot count for imageset 7:
124648 spots found on 1800 images (max 2374 / bin)
                          ********** * ********** **        
****                 ***************************************
********           *****************************************
***********     ********************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
1                         image                         1800

Histogram of per-image spot count for imageset 7:
143890 spots found on 1800 images (max 2754 / bin)
                                                *******     
***************                *****************************
*****************       ************************************
******************** ***************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
1                         image                         1800

Histogram of per-image spot count for imageset 7:
110959 spots found on 1800 images (max 2110 / bin)
                *  ** **** ************** *                 
           **********************************               
**************************************************     *** *
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
1                         image                         1800

Histogram of per-image spot count for imageset 7:
116345 spots found on 1800 images (max 2754 / bin)
                         *******                            
                       **********                           
                ********************               *        
           ********************************     ******      
        *************************************************   
* **********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
1                         image                         1800

--------------------------------------------------------------------------------
Saved 1001619 reflections to strong.refl
```

These are _not_ all from imageset 7 🤦‍♂️

### PR DESCRIPTION
**Pull request by rjgildea**
Fixes #1826

### CODE REVIEW

**Comment by graeme-winter** [comment]
I am looking at the diffs and I don't see how this fixes the problem, because I don't see how this is a problem. However I will look again in a mo once it is green and the tests are passed.

**Comment by rjgildea** [comment]
Using:
```
$ dials.import $(dials.data get -q fumarase)/*.img
$ dials.find_spots imported.expt
```
On main:
```
Histogram of per-image spot count for imageset 1:
35258 spots found on 60 images (max 1047 / bin)
*                                                           
*                                                           
*                                                          *
*                                                          *
************** ****** * *** *** ***  ******          *     *
************** ***************************** ************* *
******************************************** ***************
************************************************************
************************************************************
************************************************************
1                          image                          60

Histogram of per-image spot count for imageset 1:
37328 spots found on 60 images (max 1102 / bin)
*                                                           
*                                                           
*                                                          *
*                            *                             *
************** * *************   **   * ***                *
************** ***************************** ***************
******************************************** ***************
************************************************************
************************************************************
************************************************************
1                          image                          60
```
With this PR:
```
Histogram of per-image spot count for imageset 0:
35258 spots found on 60 images (max 1047 / bin)
*                                                           
*                                                           
*                                                          *
*                                                          *
************** ****** * *** *** ***  ******          *     *
************** ***************************** ************* *
******************************************** ***************
************************************************************
************************************************************
************************************************************
1                          image                          60

Histogram of per-image spot count for imageset 1:
37328 spots found on 60 images (max 1102 / bin)
*                                                           
*                                                           
*                                                          *
*                            *                             *
************** * *************   **   * ***                *
************** ***************************** ***************
******************************************** ***************
************************************************************
************************************************************
************************************************************
1                          image                          60
```

**Comment by rjgildea** [comment]
> I am looking at the diffs and I don't see how this fixes the problem, because I don't see how this is a problem. However I will look again in a mo once it is green and the tests are passed.

`i` was coming from the inner loop over all experiments, so it was always equal to the index of the last experiment in the list. It _should_ have come from the outer loop over imagesets.

**Review by graeme-winter — APPROVED** [review]
Now I get it it is one of those trivial but valuable fixes - thank you! Such things are annoying when you find them 🙂

+10 pts and one issue closing card

**Pull request merged**
