### PR TITLE
PIA work: select only relevant experiments

### PR DESCRIPTION
**Pull request by rjgildea**
For hdf5 grid scans, the length of the experiment is equal to the number of images in the grid scan. This results in a loop over every experiment which can add significant overhead:

https://github.com/dials/dials/blob/a66ee17aed48a59d0666eeaec78a1f8270e2c4a2/array_family/flex_ext.py#L1205-L1220

called via:

https://github.com/dials/dials/blob/a66ee17aed48a59d0666eeaec78a1f8270e2c4a2/command_line/find_spots_server.py#L117

### CODE REVIEW

**Comment by rjgildea** [comment]
Test code:
```
$ cat pia.py 
import time
import sys

from dials.command_line.find_spots_server import work


def run(filename, n):
    for i in range(n):
        parameters = ['d_max=40', f'scan_range={i+1},{i+1}']
        print(f"Starting PIA on {filename}")
        # Do the per-image-analysis
        start = time.time()
        results = work(filename, cl=parameters)
        runtime = time.time() - start
        print(
            f"PIA completed on {filename} with parameters {parameters}, results['n_spots_total'] spots found in {runtime:.2f} seconds"
        )

if __name__ == "__main__":
    run(sys.argv[1], n=10)
```

Using `main`, spotfinding takes ~1.8-2.0 seconds per image:
```
$ dials.python pia.py /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs
Starting PIA on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs
PIA completed on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs with parameters ['d_max=40', 'scan_range=1,1'], results['n_spots_total'] spots found in 8.21 seconds
Starting PIA on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs
PIA completed on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs with parameters ['d_max=40', 'scan_range=2,2'], results['n_spots_total'] spots found in 1.83 seconds
Starting PIA on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs
PIA completed on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs with parameters ['d_max=40', 'scan_range=3,3'], results['n_spots_total'] spots found in 1.84 seconds
Starting PIA on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs
PIA completed on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs with parameters ['d_max=40', 'scan_range=4,4'], results['n_spots_total'] spots found in 1.83 seconds
Starting PIA on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs
PIA completed on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs with parameters ['d_max=40', 'scan_range=5,5'], results['n_spots_total'] spots found in 1.99 seconds
Starting PIA on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs
PIA completed on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs with parameters ['d_max=40', 'scan_range=6,6'], results['n_spots_total'] spots found in 1.87 seconds
Starting PIA on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs
PIA completed on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs with parameters ['d_max=40', 'scan_range=7,7'], results['n_spots_total'] spots found in 1.88 seconds
Starting PIA on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs
PIA completed on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs with parameters ['d_max=40', 'scan_range=8,8'], results['n_spots_total'] spots found in 2.12 seconds
Starting PIA on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs
PIA completed on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs with parameters ['d_max=40', 'scan_range=9,9'], results['n_spots_total'] spots found in 2.04 seconds
Starting PIA on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs
PIA completed on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs with parameters ['d_max=40', 'scan_range=10,10'], results['n_spots_total'] spots found in 1.96 seconds
```

With the changes in this PR, spotfinding now takes ~1-1.25s per image:
```
$ dials.python pia.py /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs
Starting PIA on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs
PIA completed on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs with parameters ['d_max=40', 'scan_range=1,1'], results['n_spots_total'] spots found in 5.96 seconds
Starting PIA on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs
PIA completed on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs with parameters ['d_max=40', 'scan_range=2,2'], results['n_spots_total'] spots found in 1.23 seconds
Starting PIA on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs
PIA completed on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs with parameters ['d_max=40', 'scan_range=3,3'], results['n_spots_total'] spots found in 1.20 seconds
Starting PIA on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs
PIA completed on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs with parameters ['d_max=40', 'scan_range=4,4'], results['n_spots_total'] spots found in 1.04 seconds
Starting PIA on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs
PIA completed on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs with parameters ['d_max=40', 'scan_range=5,5'], results['n_spots_total'] spots found in 1.37 seconds
Starting PIA on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs
PIA completed on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs with parameters ['d_max=40', 'scan_range=6,6'], results['n_spots_total'] spots found in 1.19 seconds
Starting PIA on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs
PIA completed on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs with parameters ['d_max=40', 'scan_range=7,7'], results['n_spots_total'] spots found in 1.26 seconds
Starting PIA on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs
PIA completed on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs with parameters ['d_max=40', 'scan_range=8,8'], results['n_spots_total'] spots found in 1.20 seconds
Starting PIA on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs
PIA completed on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs with parameters ['d_max=40', 'scan_range=9,9'], results['n_spots_total'] spots found in 1.05 seconds
Starting PIA on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs
PIA completed on /dls/i04/data/2021/cm28182-1/20210226/swrm/gw/gridscantest_5k_500hz_extra_PIA/gridscantest_1.nxs with parameters ['d_max=40', 'scan_range=10,10'], results['n_spots_total'] spots found in 1.26 seconds
```

**Comment by graeme-winter** [comment]
I can see how the difference is substantial for _big_ grid scans, but I would welcome a similar analysis (for documentation) of e.g. an 80 image scan. 

Will test the change set in a moment and verify that it makes no difference beyond time saving.

**Comment by rjgildea** [comment]
For a 25 x 20 gridscan (500 images) there is still and appreciable speedup:
```
$ dials.python pia.py /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs 
Starting PIA on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs
PIA completed on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs with parameters ['d_max=40', 'scan_range=1,1'], results['n_spots_total'] spots found in 3.26 seconds
Starting PIA on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs
PIA completed on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs with parameters ['d_max=40', 'scan_range=2,2'], results['n_spots_total'] spots found in 0.56 seconds
Starting PIA on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs
PIA completed on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs with parameters ['d_max=40', 'scan_range=3,3'], results['n_spots_total'] spots found in 0.52 seconds
Starting PIA on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs
PIA completed on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs with parameters ['d_max=40', 'scan_range=4,4'], results['n_spots_total'] spots found in 0.41 seconds
Starting PIA on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs
PIA completed on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs with parameters ['d_max=40', 'scan_range=5,5'], results['n_spots_total'] spots found in 0.52 seconds
Starting PIA on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs
PIA completed on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs with parameters ['d_max=40', 'scan_range=6,6'], results['n_spots_total'] spots found in 0.51 seconds
Starting PIA on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs
PIA completed on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs with parameters ['d_max=40', 'scan_range=7,7'], results['n_spots_total'] spots found in 0.41 seconds
Starting PIA on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs
PIA completed on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs with parameters ['d_max=40', 'scan_range=8,8'], results['n_spots_total'] spots found in 0.50 seconds
Starting PIA on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs
PIA completed on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs with parameters ['d_max=40', 'scan_range=9,9'], results['n_spots_total'] spots found in 0.48 seconds
Starting PIA on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs
PIA completed on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs with parameters ['d_max=40', 'scan_range=10,10'], results['n_spots_total'] spots found in 0.47 seconds
```

```
$ dials.python pia.py /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs 
Starting PIA on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs
PIA completed on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs with parameters ['d_max=40', 'scan_range=1,1'], results['n_spots_total'] spots found in 3.12 seconds
Starting PIA on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs
PIA completed on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs with parameters ['d_max=40', 'scan_range=2,2'], results['n_spots_total'] spots found in 0.45 seconds
Starting PIA on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs
PIA completed on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs with parameters ['d_max=40', 'scan_range=3,3'], results['n_spots_total'] spots found in 0.35 seconds
Starting PIA on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs
PIA completed on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs with parameters ['d_max=40', 'scan_range=4,4'], results['n_spots_total'] spots found in 0.35 seconds
Starting PIA on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs
PIA completed on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs with parameters ['d_max=40', 'scan_range=5,5'], results['n_spots_total'] spots found in 0.35 seconds
Starting PIA on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs
PIA completed on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs with parameters ['d_max=40', 'scan_range=6,6'], results['n_spots_total'] spots found in 0.33 seconds
Starting PIA on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs
PIA completed on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs with parameters ['d_max=40', 'scan_range=7,7'], results['n_spots_total'] spots found in 0.35 seconds
Starting PIA on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs
PIA completed on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs with parameters ['d_max=40', 'scan_range=8,8'], results['n_spots_total'] spots found in 0.43 seconds
Starting PIA on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs
PIA completed on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs with parameters ['d_max=40', 'scan_range=9,9'], results['n_spots_total'] spots found in 0.41 seconds
Starting PIA on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs
PIA completed on /dls/i04/data/2021/cm28182-2/xraycentring/manual/xrc_26.nxs with parameters ['d_max=40', 'scan_range=10,10'], results['n_spots_total'] spots found in 0.33 seconds
```

**Review by ndevenish — COMMENTED** [review]
I guess

**Pull request merged**
