### PR TITLE
Mask generation: remove unnecessary get_raw_data()

### PR DESCRIPTION
**Pull request by rjgildea**
The mask generation code doesn't actually use the image data, but just uses the image to get the panel sizes - which are available in the panel object! This extra call to `imageset.get_raw_data()` for the first image of an imageset causes significant overhead e.g. to the per-image analysis service used at DLS.

Convert single-method class to a function.

### CODE REVIEW

**Comment by ndevenish** [comment]
Fixes https://github.com/dials/dials/issues/1449

**Review by graeme-winter — APPROVED** [review]
Clever solution to the problem, looks sane, but pls can has news fragement aimed at developers of other packages - masking is the kind of area I would imagine being used elsewhere & API change could affect them.

**Comment by ndevenish** [comment]
That's a good point - we should probably put in a `MaskGenerator` shim that prints a deprecationwarning, decide on a release and put in a `.removal`

**Comment by graeme-winter** [comment]
> That's a good point - we should probably put in a `MaskGenerator` shim that prints a deprecationwarning, decide on a release and put in a `.removal`

Probably a good idea

In fairness though, we can probaby be more assertive e.g. `MaskGenerator` throws a `RuntimeError` or something to _really let people know_ that it is gone. Keep for 1 release cycle.

**Comment by ndevenish** [comment]
That'll have the same effect as just removing - breaking the thing they are trying to do and forcing them to fix it right then and there. I don't think there is any harm in leaving in a deprecated interface for a few months.

**Comment by ndevenish** [comment]
Suggest this commit:
- `DeprecationWarning` until 3.4 (~2021-03-15)
- Then `UserWarning` until 3.5 (~2021-05-24)

**Review by ndevenish — APPROVED** [review]

**Pull request merged**
