### PR TITLE
Tests for trimming either end, verify scan OK

### PR DESCRIPTION
**Pull request by graeme-winter**
As discussed, tests which verify that the trimming works correctly i.e. does not introduce off by one errors - suspect deleting reflections manually useful way of testing but note that the test data is incomplete (by modern standards) so limits the extend to which we can really exercise this code.

### CODE REVIEW

**Comment by dagewa** [comment]
Ah but that only has images, not `indexed.expt` etc. Hmm. I know `l_cysteine_dials_output` has some `.expt` and `.refl`, but in general we could perhaps do with a few more indexed experiments in `dials_data`

**Comment by Anthchirp** [comment]
```

Scan-varying refinement
Configuring refiner
The reflections for experiment 0 do not fill the scan range. The scan will be trimmed to images {1,440} to match the range of observed data
The reflections for experiment 1 do not fill the scan range. The scan will be trimmed to images {1,453} to match the range of observed data
The reflections for experiment 2 do not fill the scan range. The scan will be trimmed to images {1,446} to match the range of observed data
The reflections for experiment 3 do not fill the scan range. The scan will be trimmed to images {1,1761} to match the range of observed data

Summary statistics for 2876 observations matched to predictions:
+-------------------+--------+----------+------------+----------+-------+
|                   |    Min |       Q1 |        Med |       Q3 |   Max |
|-------------------+--------+----------+------------+----------+-------|
| Xc - Xo (mm)      | -6.392 | -0.02824 | -0.0007747 |  0.02984 |  3.35 |
| Yc - Yo (mm)      | -3.238 | -0.02592 |   0.001963 |  0.03262 |  4.44 |
| Phic - Phio (deg) | -31.66 | -0.01436 |  -0.001682 | 0.008596 | 8.928 |
| X weights         |  182.3 |    383.5 |      399.4 |    404.3 | 405.6 |
| Y weights         |  185.6 |    371.9 |        396 |    403.8 | 405.6 |
| Phi weights       |    240 |     1168 |       1188 |     1197 |  1200 |
+-------------------+--------+----------+------------+----------+-------+

Detecting centroid outliers using the MCD algorithm
641 reflections have been flagged as outliers
2235 reflections remain in the manager

Summary statistics for 2235 observations matched to predictions:
+-------------------+----------+-----------+------------+----------+---------+
|                   |      Min |        Q1 |        Med |       Q3 |     Max |
|-------------------+----------+-----------+------------+----------+---------|
| Xc - Xo (mm)      |  -0.1484 |  -0.02218 |  0.0001333 |  0.02566 |  0.1664 |
| Yc - Yo (mm)      |  -0.1738 |  -0.02282 |  0.0002451 |  0.02512 |  0.2213 |
| Phic - Phio (deg) | -0.06328 | -0.008471 | -5.637e-05 | 0.008316 | 0.06368 |
| X weights         |      212 |     390.7 |      400.9 |    404.5 |   405.6 |
| Y weights         |    208.9 |     380.5 |        398 |      404 |   405.6 |
| Phi weights       |      864 |      1173 |       1189 |     1197 |    1200 |
+-------------------+----------+-----------+------------+----------+---------+

Too few reflections to parameterise Crystal4Phi1_sample3, Crystal4Phi1_sample4, Crystal4Phi1_sample5, Crystal4Phi2_sample3, Crystal4Phi2_sample4, Crystal4Phi2_sample5, Crystal4Phi3_sample3, Crystal4Phi3_sample4, Crystal4Phi3_sample5, Crystal4g_param_0_sample3, Crystal4g_param_0_sample4, Crystal4g_param_0_sample5, Crystal4g_param_1_sample3, Crystal4g_param_1_sample4, Crystal4g_param_1_sample5, Crystal4g_param_2_sample3, Crystal4g_param_2_sample4, Crystal4g_param_2_sample5, Crystal4g_param_3_sample3, Crystal4g_param_3_sample4, Crystal4g_param_3_sample5, Crystal4g_param_4_sample3, Crystal4g_param_4_sample4, Crystal4g_param_4_sample5, Crystal4g_param_5_sample3, Crystal4g_param_5_sample4, Crystal4g_param_5_sample5.
Try modifying refinement.parameterisation.auto_reduction options
```

**Comment by Anthchirp** [comment]
another concern I have is that the test run takes 45 seconds for both the start and the end test.

**Comment by dagewa** [comment]
Looking at this now. Perhaps these tests are not really necessary, because the function used is already tested here
https://github.com/dials/dials/blob/df3e4f25bc2bcb8e193fda91407d09f251a9f692/test/algorithms/refinement/test_refiner_config.py#L56

**Comment by ndevenish** [comment]
# [Codecov](https://codecov.io/gh/dials/dials/pull/1052?src=pr&el=h1) Report
> Merging [#1052](https://codecov.io/gh/dials/dials/pull/1052?src=pr&el=desc) into [master](https://codecov.io/gh/dials/dials/commit/8631c9b6f5cc7956e5d40b11e24be91f6afe5502&el=desc) will **increase** coverage by `0.02%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/dials/dials/pull/1052?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master    #1052      +/-   ##
==========================================
+ Coverage   70.68%   70.70%   +0.02%     
==========================================
  Files         609      610       +1     
  Lines       68587    68643      +56     
  Branches     8519     8525       +6     
==========================================
+ Hits        48480    48535      +55     
+ Misses      18228    18225       -3     
- Partials     1879     1883       +4     
```


| [Impacted Files](https://codecov.io/gh/dials/dials/pull/1052?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [algorithms/indexing/indexer.py](https://codecov.io/gh/dials/dials/pull/1052/diff?src=pr&el=tree#diff-YWxnb3JpdGhtcy9pbmRleGluZy9pbmRleGVyLnB5) | `77.69% <0.00%> (-0.53%)` | :arrow_down: |
| [algorithms/indexing/lattice\_search/\_\_init\_\_.py](https://codecov.io/gh/dials/dials/pull/1052/diff?src=pr&el=tree#diff-YWxnb3JpdGhtcy9pbmRleGluZy9sYXR0aWNlX3NlYXJjaC9fX2luaXRfXy5weQ==) | `77.11% <0.00%> (-0.50%)` | :arrow_down: |
| [algorithms/integration/test\_processor.py](https://codecov.io/gh/dials/dials/pull/1052/diff?src=pr&el=tree#diff-YWxnb3JpdGhtcy9pbnRlZ3JhdGlvbi90ZXN0X3Byb2Nlc3Nvci5weQ==) | `100.00% <0.00%> (ø)` | |
| [algorithms/refinement/refiner.py](https://codecov.io/gh/dials/dials/pull/1052/diff?src=pr&el=tree#diff-YWxnb3JpdGhtcy9yZWZpbmVtZW50L3JlZmluZXIucHk=) | `81.04% <0.00%> (+0.38%)` | :arrow_up: |

------

[Continue to review full report at Codecov](https://codecov.io/gh/dials/dials/pull/1052?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/dials/dials/pull/1052?src=pr&el=footer). Last update [8631c9b...db4297b](https://codecov.io/gh/dials/dials/pull/1052?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by graeme-winter** [comment]
> Looking at this now. Perhaps these tests are not really necessary, because the function used is already tested here
> https://github.com/dials/dials/blob/df3e4f25bc2bcb8e193fda91407d09f251a9f692/test/algorithms/refinement/test_refiner_config.py#L56

If not necessary will close

**Pull request closed without merging**
