### PR TITLE
re-enable Azure Windows builds

### PR DESCRIPTION
**Pull request by Anthchirp**
They will be horribly slow until we stop building cbflib

### CODE REVIEW

**Comment by Anthchirp** [comment]
So the runtime is now on the same order of magnitude as linux and mac builds, so in principle this can be merged. Might want to look into that failing pickle test though. (Appreciate this is the aim of #1651)

**Comment by Anthchirp** [comment]
And we should probably document somewhere that Python 3.6 is not supported on Windows

**Comment by dagewa** [comment]
Sounds good. I'm happy to write a "Building DIALS on Windows" webpage. I suppose we are still some way off providing installable builds.

We should also clearly document that Windows support is still limited, due to lack of multiprocessing. That's something I want to look into, but I think it's going to be a case of making everything I look at pickleable, which is going to be quite some work.

**Comment by Anthchirp** [comment]
To be honest we can document the lack of support in the code quite easily...

**Pull request merged**
