### PR TITLE
Remove cctbx.xfel dependency from dials.index

### PR DESCRIPTION
**Pull request by jbeilstenedmands**
A port of two functions from `cctbx.xfel` to remove the dependency on `cctbx.xfel` for stills indexing.

For https://github.com/dials/dials/issues/2389, https://github.com/dials/dials/issues/2076

### CODE REVIEW

**Comment by phyy-nx** [comment]
Hi @jbeilstenedmands I have an alternate approach I'm working on.  I'll show it off in tomorrow's dials core if that's ok.  Thanks!

**Comment by jbeilstenedmands** [comment]
Hi @phyy-nx , no problem, my idea was to get this out in the open for discussion at the core meeting, happy to consider alternative approaches.

**Comment by graeme-winter** [comment]
I will note that the fundamental issue is however circular dependencies. Any effort to make the graphs acyclic will be much appreciated.

**Comment by phyy-nx** [comment]
Conversation here: https://github.com/dials/dials/issues/2076#issuecomment-1518443920

**Comment by jbeilstenedmands** [comment]
Closing, as https://github.com/dials/dials/pull/2404 will provide the solution to the issue

**Comment by ndevenish** [comment]
After internal discussion we decided that we'd like to reconsider merging this, so that we can get e.g. serial tooling working on conda builds - and to revert when the alternate serialtbx stuff is ready to go.

To be discussed in the meeting later this week, I guess.

**Comment by ndevenish** [comment]
After discussion at DIALS-core, we've agreed to merge this for release, but to add the immediate revert to https://github.com/dials/dials/pull/2404 so that it's undone when serialtbx is ready.

**Pull request merged**
