### PR TITLE
dials.reindex: adding reindexing against a reference reflection file

### PR DESCRIPTION
**Pull request by jbeilstenedmands**
This pull request aims to introduce additional functionality to dials.reindex,
allowing reindexing against a reference dataset in the case of twinning.
Made a pull request to allow people the chance to give feedback
before merging.

If a reference reflections.pickle and experiments.json are given, the
space group (must be same for both datasets) is tested for potential
twinning operators. If these exist, the test dataset is reindexed to all
possible settings, and the reindexing that gives the best correlation to
the reference is used to reindex the data. The 'correlation' is simply the
correlation coefficient between the datasets (no renormalisation yet,
could be implemented to improve in future).

The naming of the command line options is a little unsatisfying, as there
already exists a `reference=` option to specify an experiments file, so I've
just added a `reference_reflections=` option. Would it be better to add
another parameter `reference_experiments=` and make a clear distinction
between the two types of reference reindexing?

I've added a trivial command line dataset test, but will look for a better
example when adding scaling test datasets.

### CODE REVIEW

**Comment by ndevenish** [comment]
So I tried this on non-twinned cubic data that was misoriented with respect to another dataset on the same (P4) crystal and it didn't seem to reindex. Am I misinterpreting the intention of this or would this be something sensible to do?

**Comment by jbeilstenedmands** [comment]
Yes this is an intended use case, can you copy in the output from dials.reindex?

**Comment by ndevenish** [comment]
Sure. This isn't urgent though so feel free to leave. Unless I'm being blind/stupid, the crystal orientation should have changed here, but hasn't:

```
RH7 ws133 02$ pwd
/dls/tmp/mep23677/tmp.YZUaqEbGcT/n11/02

RH7 ws133 02$ dials.reindex integrated.pickle integrated_experiments.json reference.experiments=../01/integrated_experiments.json reference.reflections=../01/integrated.pickle
The following parameters have been modified:

reference {
  experiments = "../01/integrated_experiments.json"
  reflections = "../01/integrated.pickle"
}
input {
  experiments = integrated_experiments.json
  reflections = integrated.pickle
}

No twin operators found, no reindexing required

Old crystal:
Crystal:
    Unit cell: (77.981(14), 77.981(14), 37.982(6), 90.0, 90.0, 90.0)
    Space group: P 43 21 2
    U matrix:  {{-0.3010,  0.2535,  0.9193},
                {-0.5904,  0.7075, -0.3884},
                {-0.7489, -0.6596, -0.0633}}
    B matrix:  {{ 0.0128,  0.0000,  0.0000},
                {-0.0000,  0.0128,  0.0000},
                { 0.0000,  0.0000,  0.0263}}
    A = UB:    {{-0.0039,  0.0033,  0.0242},
                {-0.0076,  0.0091, -0.0102},
                {-0.0096, -0.0085, -0.0017}}


New crystal:
Crystal:
    Unit cell: (77.981, 77.981, 37.982, 90.000, 90.000, 90.000)
    Space group: P 43 21 2
    U matrix:  {{-0.3010,  0.2535,  0.9193},
                {-0.5904,  0.7075, -0.3884},
                {-0.7489, -0.6596, -0.0633}}
    B matrix:  {{ 0.0128,  0.0000,  0.0000},
                {-0.0000,  0.0128,  0.0000},
                { 0.0000,  0.0000,  0.0263}}
    A = UB:    {{-0.0039,  0.0033,  0.0242},
                {-0.0076,  0.0091, -0.0102},
                {-0.0096, -0.0085, -0.0017}}


Saving reindexed experimental models to reindexed_experiments.json
Saving reindexed reflections to reindexed_reflections.pickle
```
But I think there should be a change of basis applied:
```
RH7 ws133 02$ dials.compare_orientation_matrices integrated_experiments.json ../01/integrated_experiments.json
The following parameters have been modified:

input {
  experiments = integrated_experiments.json
  experiments = ../01/integrated_experiments.json
}

Change of basis op: b,a,-c
Rotation matrix to transform crystal 1 to crystal 2:
{{1.000, 0.006, -0.001},
 {-0.006, 1.000, -0.000},
 {0.001, 0.000, 1.000}}
Rotation of -0.331 degrees about axis (-0.071, 0.246, 0.967)
```

**Comment by jbeilstenedmands** [comment]
It looks like my code is not doing what I expect:

No twin operators found, no reindexing required

This bit is done by a module in mmtbx, but there should be some operators for this space group, so maybe I'm not using it correctly: this is something for me to look at next week, sorry!

Thanks for the report.

**Comment by ndevenish** [comment]
I've filed ticket #617 so discussion/work next week isn't happening on a closed pull request

**Comment by graeme-winter** [comment]
P4 has twinning operators but 422 does not. Probably the code is doing the right thing as there is no ambiguity.

**Pull request merged**
