### PR TITLE
Remove custom DIALS tqdm

### PR DESCRIPTION
**Pull request by Anthchirp**
Remove DIALS tqdm customizations and use unmodified, plain tqdm code instead. Retain the changed defaults when imported via `dials.util.progress`.

This allows wider compatibility with `tqdm` versions, resolving #1255, and allows updating the tqdm version (not part of this pull request), which fixes some Python 3.8 compatibility issues (#1236).

### CODE REVIEW

**Comment by ndevenish** [comment]
Yes, happy with this, I was thinking about it earlier today in fact. I can’t remember if it tried to detect tty capture (to avoid messing up logs) but we can always handle that separately.

**Comment by Anthchirp** [comment]
oh joy, this is _ludicrous_.

Removing our custom tqdm modifications randomly (yet reproducibly) breaks MacOS >=Catalina on Python 3.7, because matplotlib 3.2 opens a font file (but doesn't read it - to conserve memory), the handle of which is then `spawn()`ed to multiprocessing children that then try to close that file and :boom:.
```
(1000 line stack trace skipped)
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't close file
```

There are three solutions here:
1. switch to multiprocessing forkserver, which is what this PR does.
2. (apparently) go directly to Python 3.8, do not pass go, do not support 3.7.
3. update to matplotlib 3.3. Unfortunately that one has only just reached the rc1 release stage.

**Comment by ndevenish** [comment]
I don't think it's unreasonable to change for the tests, seeing as that's the only time when we use matplotlib before multiprocessing. I wondered for a bit if changing to `spawn` might be more appropriate in advance of that being the default anyway, but guess it's not too bad since it's constrained to 3.7 only.

I'm still not clear why this only happens for 3.7 and why removing this code triggered the problem. I'm wondering it it's a test ordering edge case triggered by the test being removed, and that this change should be separate from this removal (even though the removal exhibited the problem)

**Comment by Anthchirp** [comment]
I don't know. I also don't have access to an interactive system where I can test this. The build mac mini could not reproduce the issue at all, but that should be because it is pre-Catalina.

**Pull request merged**
