### PR TITLE
select_rows_index: use the experiment_identifiers map as a map

### PR DESCRIPTION
**Pull request by dwpaley**
When selecting the odd experiments in a large reflection table from a serial dataset, this improves the time for the select statement from ~10 min to ~1 second.
[refl.pickle.zip](https://github.com/dials/dials/files/10263571/refl.pickle.zip)
After unzipping the attached `refl.pickle`, time this test script:
```
from dials.array_family import flex
refl = flex.reflection_table.from_file('refl.pickle')
sel = refl['id'] %2 == 1
refl.select(sel)

```

### CODE REVIEW

**Comment by dwpaley** [comment]
Ok, tests pass now.

**Comment by phyy-nx** [comment]
Bump :)
@jbeilstenedmands

**Review by jbeilstenedmands — APPROVED** [review]
Apologies, I hadn't noticed the review request, thanks for the reminder. That's a great runtime improvement, nice one!

**Comment by dwpaley** [comment]
Thanks!

**Pull request merged**
