### PR TITLE
Add dials.merge and finish off post-integration workflow

### LINKED ISSUE #826: Finishing off the data reduction workflow in DIALS
Something that has become apparent at workshops is that we need to be handling the workflow a bit better after scaling. Currently, you can't take a scaled (unmerged) mtz file into ccp4 for further processing without running the whole pointless/aimless data reduction task. In ccp4 you can import a merged mtz - but this can only be generated by dials.scale with option merged_mtz=.

Suggested solutions include having a merged mtz option for dials export, letting dials.scale output a merged scaled mtz by default in dials.scale, or creating a separate program for merging data from a reflection table. If using a separate program (maybe dials.merge), this could also include a truncate analysis and extensive statistics reporting.
This last solution feels the tidiest - in this sense dials could replicate the ccp4 workflow;
pointless > aimless > ctruncate = dials.symmetry > dials.scale > dials.merge. This would also let dials processing finish at the same point as xia2. Of course dials.export would still exist, so there would be the option of having an unmerged+scaled mtz of Is, or merged+truncated mtz of Fs, depending on preferences for downstream processing.

### PR DESCRIPTION
**Pull request by jbeilstenedmands**
This pull request introduces dials.merge, a command line program to create a merged, truncated mtz from scaled.refl, scaled.expt. This merges the data, truncates using the french_wilson miller array method, prints the Wilson statistics and merging statistics before exporting to mtz. Fixes #826 
If multi-wavelength data is present, the merged mtz contains two datasets, one for each wavelength.

There will be an equivalent pull request to update the dials-full pipeline in xia2 to use the updated programs which should be merged at the same time.

dials.merge main options (and defaults);

- truncate = True (turn off to not truncate - no Fs in output just Is). Turning off changes default filename from truncated.mtz to scaled_merged.mtz

- anomalous = True (turn off to only output mean Is & Fs)

- assess_space_group = True (currently runs dials.space_group, in future when all is rolled into dials.symmetry, it would run dials.symmetry but maybe False by default)

As part of this work, dials.scale was also simplified to call the new dials.merge code to improve consistency, as well as removing a few hacky options that were put in for xia2 that are now redundant.

With these (and recent) changes, the post-integration workflow is as follows:
post_integration_workflow

Example of default mtz output (thaumatin example dataset):
```
Writing reflections to truncated.mtz
Title: From dials.merge
Space group symbol from file: P41212
Space group number from file: 92
Space group from matrices: P 41 21 2 (No. 92)
Point group symbol from file: 422
Number of crystals: 1
Number of Miller indices: 71077
Resolution range: 150.001 1.16996
History:
  From DIALS 2.dev.568-gac9b16a59, run on 2019-07-19 at 15:18:43 BST  (2019-07-19
Crystal 1:
  Name: DIALS
  Project: DIALS
  Id: 1
  Unit cell: (57.7835, 57.7835, 150.001, 90, 90, 90)
  Number of datasets: 1
  Dataset 1:
    Name: FROMDIALS
    Id: 1
    Wavelength: 1
    Number of columns: 17
    label    #valid  %valid   min     max type
    H         71077 100.00%  0.00   47.00 H: index h,k,l
    K         71077 100.00%  0.00   33.00 H: index h,k,l
    L         71077 100.00%  0.00  114.00 H: index h,k,l
    IMEAN     71077 100.00% -7.67 4040.99 J: intensity
    SIGIMEAN  71077 100.00%  0.01   61.38 Q: standard deviation
    I(+)      69611  97.94% -7.67 4040.99 K: I(+) or I(-)
    SIGI(+)   69611  97.94%  0.01   61.38 M: standard deviation
    I(-)      56579  79.60% -7.72 3049.79 K: I(+) or I(-)
    SIGI(-)   56579  79.60%  0.22   46.70 M: standard deviation
    N(+)      69611  97.94%  2.00    8.00 I: integer
    N(-)      56579  79.60%  8.00    8.00 I: integer
    F         71070  99.99%  0.03   63.50 F: amplitude
    SIGF      71070  99.99%  0.02    1.05 Q: standard deviation
    F(+)      69607  97.93%  0.03   63.50 G: F(+) or F(-)
    SIGF(+)   69607  97.93%  0.02    1.05 L: standard deviation
    F(-)      56575  79.60%  0.56   55.14 G: F(+) or F(-)
    SIGF(-)   56575  79.60%  0.07    0.87 L: standard deviation
```

### CODE REVIEW

**Comment by graeme-winter** [comment]
```
dials.import /Users/graeme/data/i04-eiger-small/Therm_6_2_master.h5 
dials.find_spots imported.expt nproc=8
dials.index imported.expt strong.refl 
dials.refine indexed.* scan_varying=1
dials.integrate refined* nproc=8
dials.symmetry integrated.*
dials.scale symmetrized.*
dials.space_group scaled*
dials.merge symmetrized.expt scaled.refl
```

appeared to do what I would expect 🙂

not convinced by `truncated.mtz` - maybe `scaled_with_F.mtz` better?

**Comment by dagewa** [comment]
I'm not sure having the default output filename change dependent on program options is useful. Perhaps it should just be `merged.mtz` in any case. The user can always be encouraged to set their own filename to something that is more meaningful to them.

I'll have a proper look through next week.

**Comment by jbeilstenedmands** [comment]
Thanks for the initial feedback. I have considered this and think I now agree with you @dagewa. It's perhaps not worth making a significant distinction based on the truncation (and not worth having to explain truncation for a basic workflow) - so just ```merged.mtz``` would be neater, give us more flexibility to tinker in future and the workflow would be simplified to this:
post_integration_workflow_2

I'm happy for this to sit around for a week or so for testing so no rush 🙂

**Comment by dagewa** [comment]
I tried with one dataset and got the same screw axes as Pointless, so in that limited test :+1: 

It isn't a great dataset. I noticed the log contains a lot of rejects. These just end up as screenfuls of a not-very-nicely-formatted table (and a typo in the header). Might be better to use `simple_table`, and maybe print this only at `-v` level once #866 is merged?

```** Calculating bin mean intensity values for each intensity **
** Total # rejected intensities: 521 **
** Summary or rejected intensities **
-----------------------------------------------------------------
Miller Index  :  Intensity  :  Sigma  :  Bin Mean Intensity
(-1, -4, -52)    -13.576      50.559    12.820
(-13, -1, -43)    4.280      65.979    10.701
(-1, -5, -52)    -4.729      50.135    11.517
(1, 5, 52)    3.260      62.719    11.517
(-21, -3, -20)    -7.992      39.309    9.461
(1, 2, 53)    -14.899      35.764    9.514
(-22, -4, -13)    -1.808      37.049    9.179
(-21, -3, -21)    -7.148      38.570    8.715
(-19, -15, -20)    29.553      44.254    9.226
(-19, -14, -22)    -2.428      37.456    8.768
(-14, -3, -42)    13.010      41.051    9.041
(-11, -14, -42)    -4.489      37.062    9.331
(-1, -13, -50)    -10.482      33.314    8.898
(1, 5, 53)    -7.694      35.053    8.726
(13, 1, 44)    -0.346      40.513    8.864
(13, 2, 44)    -13.560      39.657    8.722
(-22, -4, -15)    -2.831      32.357    7.894
...
...
...
```

Are you planning to make the changes so that the default filename is `merged.mtz` and to move the symmetry check out of dials.merge in this PR, or make those changes later?

**Comment by jbeilstenedmands** [comment]
Thanks David, I've changed the filename and French-Wilson output now.
I was planning to move the space group checks to dials.symmetry at a later stage as this might be a bit of a bigger job, and I'd like to have a go at expanding the space group check to all space groups first.

**Comment by graeme-winter** [comment]
Reviewing now - sorry for delay!

**Comment by graeme-winter** [comment]
`dials.merge` tells me

```
------------------------
| Space group | score  |
------------------------
| P 4 2 2     | 0.0000 |
| P 4 21 2    | 0.0016 |
| P 41 2 2    | 0.0000 |
| P 42 2 2    | 0.0000 |
| P 41 21 2   | 0.9984 |
| P 42 21 2   | 0.0000 |
------------------------
Recommended space group: P 41 21 2
Space group with equivalent score (enantiomorphic pair): P 43 21 2

Scaling input intensities via French-Wilson Method
Total number of rejected intensities 6830
```

but does not act on this - the MTZ is output as 

```
 * Space group = 'P422' (number     89)
```

which is probably not what we want...

**Comment by graeme-winter** [comment]
Reindexed then ran refmac on the MTZ file with 1RQW as input (with some thaumatin data) - worked fine 

```
 $$
 $TEXT:Result: $$ Final results $$
                      Initial    Final
           R factor    0.2517   0.2024
     Rms BondLength    0.0635   0.0116
      Rms BondAngle    2.7010   1.7348
     Rms ChirVolume    0.1265   0.0847
 $$
```

however some concerns - weighted R values are unprintable - 

```
Resolution limits                    =     57.693     1.500
Number of used reflections           =      41517
Percentage observed                  =    99.9615
Percentage of free reflections       =     0.0000
Overall R factor                     =     0.2024
Average Fourier shell correlation    =     0.7856
Overall weighted R factor            = 52375.3086
Overall weighted R2 factor           = **********
Average correlation coefficient      =     0.7931
Overall correlation coefficient      =     0.9620
Cruickshanks DPI for coordinate error=     0.0745
Overall figure of merit              =     0.6966
ML based su of positional parameters =     0.0810
ML based su of thermal parameters    =     2.5907
```

literally, which makes me think SIGF is probably ... not ideal. Maps look OK though so F's are F like.

**Comment by graeme-winter** [comment]
Also seems to write the wrong wavelength to the MTZ header?

```

 * Dataset ID, project/crystal/dataset names, cell dimensions, wavelength:

        1 DIALS
          DIALS
          FROMDIALS
             57.6927   57.6927  149.8403   90.0000   90.0000   90.0000
             1.00000
```

compared with

```
Beam:
    wavelength: 0.980274
    sample to source direction : {0,0,1}
    divergence: 0
    sigma divergence: 0
    polarization normal: {0,1,0}
    polarization fraction: 0.999
```

which is more of a concern... N.B. dials.export on scaled data gives:

```
 * Dataset ID, project/crystal/dataset names, cell dimensions, wavelength:

        1 DIALS
          XTAL
          FROMDIALS
             57.6927   57.6927  149.8403   90.0000   90.0000   90.0000
             0.98027
```

from 

`dials.export scaled.refl scaled.expt intensity=scale mtz.hklout=scaled.mtz`

**Comment by graeme-winter** [comment]
I will make a script which should work with an example data set to allow comparison with pre-existing tools (e.g. ctruncate) to give an is-it-a-direct-replacement assessment.

**Comment by dagewa** [comment]
I think in previous discussion (not sure where now) we concluded that dials.merge should not be changing the space group. The systematic absences check would instead be rolled into dials.symmetry, and then the recommended workflow would be to run dials.symmetry a second time, after dials.scale and before dials.merge

**Comment by dagewa** [comment]
Found it (in slack). @jbeilstenedmands' conclusion was to put the sys abs check into dials.symmetry, and then run dials.symmetry again at the first part of dials.merge, raising a warning or error if the result was different to before

**Comment by graeme-winter** [comment]
@dagewa 10-4 - makes sense - other comments still stand though 🙂 will produce a test case

**Comment by jbeilstenedmands** [comment]
Thanks for the review Graeme. There's also a xia2 pull request to update dials-full to using the new tools, if you don't mind testing that too.

**Pull request merged**
