### PR TITLE
No trusted range for spotfinding

### PR DESCRIPTION
**Pull request by dagewa**
Is this the right way to deprecate something, just emit a `logger.warning`?

### CODE REVIEW

**Comment by Anthchirp** [comment]
No, you want to 
```python
import warnings
warnings.warn("Text", DeprecationWarning)
```

**Comment by dagewa** [comment]
done, but this is not visible

**Comment by graeme-winter** [comment]
@dagewa the warning will be visible if used in a test environment

**Comment by graeme-winter** [comment]
Does get me wondering though

If we have a PHIL parameter which has been deprecated should we be able to add a deprecate flag & warn in the PHIL parsing if it gets set from it's initial value? 🤔 May ticket this.

**Comment by rjgildea** [comment]
As mentioned [here](https://github.com/cctbx/cctbx_project/issues/452#issuecomment-604313748) there is already a `.deprecated` attribute in phil. This emits a warning with `warnings.warn` if the parameter is used (although a user wouldn't actually see the warning by default).

**Comment by dagewa** [comment]
In this particular case, the deprecation message is more for users than developers. I would like it if such messages ended in stdout and the log, automatically. I thought `logging.captureWarnings(True)` should do it, but it appeared not to.

**Comment by rjgildea** [comment]
This does appear to output a warning to users:
```
$ cat deprecated.py 
import libtbx.phil

phil_scope = libtbx.phil.parse("""\
a = None
    .deprecated = True
""")
params = phil_scope.fetch(libtbx.phil.parse("a=1"))
params.show()
$ libtbx.python deprecated.py 
/Users/rjgildea/software/cctbx/modules/cctbx_project/libtbx/phil/__init__.py:1012: PhilDeprecationWarning: a is deprecated - not recommended for use.
  self.full_path(), PhilDeprecationWarning)
```

See also:
https://github.com/cctbx/cctbx_project/blob/b0210c194b5819365f4a968240312585568b7241/libtbx/phil/__init__.py#L20-L22
and
https://github.com/cctbx/cctbx_project/blob/b0210c194b5819365f4a968240312585568b7241/libtbx/phil/__init__.py#L1011-L1012

**Comment by Anthchirp** [comment]
Apparently the appropriate warning category if you want to tell users about deprecated features is
[`FutureWarning`](https://docs.python.org/3/library/exceptions.html#FutureWarning) as per [PEP565](https://www.python.org/dev/peps/pep-0565/#additional-use-case-for-futurewarning).

So the most careful deprecation path would be
`PendingDeprecationWarning` :arrow_right: `DeprecationWarning` :arrow_right: `FutureWarning` :arrow_right: feature removal

`PendingDeprecationWarnings` could be used to backport deprecation warnings, ie. if a feature was marked as deprecated or removed _after_ a release was made then that feature could be marked as will-be-deprecated-in-the-future in the next point release. Users would be none-the-wiser, but developers building on it would see harmless test output that can be bulk-ignored if so desired.

I'll add a commit here to change this PR to `FutureWarning`.

**Comment by ndevenish** [comment]
This seems to work and is probably something we want in a X.Y.0 release so going to merge

**Pull request merged**
