### PR TITLE
Sparse scan-varying refinement

### LINKED ISSUE #1800: Scan-varying refinement with the SparseLevMar engine is unhelpful
Following the question in https://github.com/dials/dials/discussions/1521#discussioncomment-905551, I took a 3600 image, 360° test dataset and tried scan-varying refinement leaving the refinement engine as default (`LevMar`) or setting it to `SparseLevMar`.

In either case,
```
There are 115 parameters to refine against 153095 reflections in 3 dimensions
```

1. Dense case
```
/usr/bin/time -v dials.refine -vv indexed.{expt,refl} scan_varying=True
...
Elapsed (wall clock) time (h:mm:ss or m:ss): 1:23.84
Maximum resident set size (kbytes): 3568632
```

2. Sparse case
```
/usr/bin/time -v dials.refine -vv indexed.{expt,refl} scan_varying=True engine=SparseLevMar
...
Elapsed (wall clock) time (h:mm:ss or m:ss): 2:03.69
Maximum resident set size (kbytes): 10605640
```

Surprisingly, the "sparse" job took considerably longer and used nearly 3 times as much memory. Both jobs took 11 steps with identical RMSDs at each step. The final models are equivalent, except that the `SparseLevMar` job does not calculate unit cell errors, whereas the default job does.

### PR DESCRIPTION
**Pull request by dagewa**
This PR enables better use of sparse storage during gradient calculation for scan-varying parameterisations. This avoids the storage of a large number of explicit zero elements. For a 3600 image, 360° test dataset this reduces the overall memory requirement of a `dials.refine scan_varying=true` to 93% of that required on the main branch. This saving should be improved for larger scans, i.e. multi-turn data collection, as sparseness of the Jacobian increases. As well as the memory reduction, total wall clock time for the run is reduced to 77% of the main branch (see #1800).

Fixes #1800.

### CODE REVIEW

**Comment by dagewa** [comment]
Tagged @graeme-winter for review, and testing with multi-turn datasets

**Comment by graeme-winter** [comment]
Noted, wilco, just processing a ... 10-turn data set right now

**Comment by graeme-winter** [comment]
Right, this is going to be a process... 

```
        Command being timed: "dials.refine ../indexed.expt ../indexed.refl"
        User time (seconds): 6713.07
        System time (seconds): 118.45
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 1:53:55
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 38208560
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 83111430
        Voluntary context switches: 8595
        Involuntary context switches: 2728
        Swaps: 0
        File system inputs: 0
        File system outputs: 8
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

timing for 1st run, on main, in P1

**Comment by graeme-winter** [comment]
Not P1, I23

```
        Command being timed: "dials.refine ../i23.expt ../i23.refl"
        User time (seconds): 1894.68
        System time (seconds): 56.56
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 32:34.73
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 20295136
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 36415813
        Voluntary context switches: 8592
        Involuntary context switches: 955
        Swaps: 0
        File system inputs: 0
        File system outputs: 8
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

**Comment by graeme-winter** [comment]
Branch; i23

```
        Command being timed: "dials.refine ../i23.expt ../i23.refl"
        User time (seconds): 1542.23
        System time (seconds): 28.70
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 26:21.68
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 20295900
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 832
        Minor (reclaiming a frame) page faults: 20870183
        Voluntary context switches: 12435
        Involuntary context switches: 643
        Swaps: 0
        File system inputs: 429744
        File system outputs: 8
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

**Comment by graeme-winter** [comment]
P1 on the branch

```
        Command being timed: "dials.refine ../indexed.expt ../indexed.refl"
        User time (seconds): 5928.33
        System time (seconds): 66.51
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 1:39:59
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 38212152
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 41046323
        Voluntary context switches: 8619
        Involuntary context switches: 2055
        Swaps: 0
        File system inputs: 0
        File system outputs: 8
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

**Comment by dagewa** [comment]
A reduction in wallclock time is good to see, but it is surprising there is essentially no reduction in memory requirements. With the 360° test dataset I saw a reduction to 93% of the memory requirement - so not a large reduction but measurable. I thought this would improve with more parameters, but maybe the memory is going somewhere else. I'm looking at the 10-turn datasets now...

**Comment by dagewa** [comment]
Here's some analysis of the Jacobian structure on this branch for the 10-turn data set, starting with a single-step scan-varying refinement run. First for the I23 case:
```
dials.refine scan_varying=True max_iterations=1\
  track_jacobian_structure=True history=history_I23.json\
  ../i23.expt ../i23.refl 
```
Then extract the Jacobian structure and plot:
```python
import json
import sys
from matplotlib import pyplot as plt

with open("history.json") as f:
    history = json.load(f)
jacobian_structure = history["data"]["jacobian_structure"][-1]
iparam = [i for i in range(len(jacobian_structure))]

structural_zeroes = [param["structural_zeroes"] for param in jacobian_structure]
all_zeroes = [param["all_zeroes"] for param in jacobian_structure]
all_rows = [param["nrows"] for param in jacobian_structure]
explicit_zeroes = [a-b for a,b in zip(all_zeroes, structural_zeroes)]
non_zeroes = [a-b for a,b in zip(all_rows, all_zeroes)]

fig, ax = plt.subplots()
ax.bar(iparam, structural_zeroes, label='Structural zeroes', width=1.0)
ax.bar(iparam, explicit_zeroes, label='Explicit zeroes', bottom=structural_zeroes, width=1.0)
ax.bar(iparam, non_zeroes, label='Non-zeroes', bottom=all_zeroes, width=1.0)
ax.legend(loc="lower right")
ax.set_ylabel("Rows")
ax.set_xlabel("Parameters")
ax.set_title("Jacobian structure")

plt.savefig("structure_I23.png", dpi=300)
```
structure_I23
This indicates that the Jacobian truly is sparse, with no explicit zeroes visible.

**Comment by dagewa** [comment]
Likewise for P1
structure_P1
In this case there are a very small number of explicit zeroes visible, which are when we get crystal parameters that cannot be determined for particular reflections (e.g. length of unit cell vector parallel to the beam at some orientation).

**Comment by dagewa** [comment]
This branch does not change the default refinement engine, only the sparseness of the Jacobian. One thing that seemed worth exploring is whether setting `engine=SparseLevMar` makes a difference, as this would use not only a sparse Jacobian, but a sparse normal matrix as well.

**`engine=LevMar`** (default)
```
Command being timed: "dials.refine scan_varying=True track_jacobian_structure=True ../i23.expt ../i23.refl max_iterations=1"
	User time (seconds): 115.05
	System time (seconds): 3.99
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 1:59.51
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 6948076
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 4550607
	Voluntary context switches: 66
	Involuntary context switches: 628
	Swaps: 0
	File system inputs: 2008
	File system outputs: 1423256
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

**`engine=SparseLevMar`**
```
	Command being timed: "dials.refine scan_varying=True track_jacobian_structure=True ../i23.expt ../i23.refl max_iterations=1 engine=SparseLevMar"
	User time (seconds): 110.34
	System time (seconds): 6.96
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 1:57.84
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 10517444
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 8899464
	Voluntary context switches: 47
	Involuntary context switches: 903
	Swaps: 0
	File system inputs: 0
	File system outputs: 1423272
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

No, that didn't help! Peak memory requirements for `SparseLevMar` are 1.5 times higher than `LevMar` (for this job)

**Comment by dagewa** [comment]
The purpose of this branch is to properly account for sparseness during gradient calculations for scan-varying refinement. The plots indicate that has been achieved. However, it appears this only translates to a modest improvement in overall performance of `dials.refine`. Further reduction in the memory footprint would have to be explored outside the gradient calculations. I don't think that should occur on this branch though.

**Comment by dagewa** [comment]
Ok, something strange going on here. I tried a full scan-varying run on branch vs main, and I get a _very significant_ difference in run time and memory requirements. The branch takes 1/3 of the time and uses 1/3 of the memory than main. At least, according to `mprof`. I'll follow up with `/usr/bin/time -v` runs next.

Command: `dials.python -m mprof run /home/fcx32934/sw/cctbx/modules/dials/command_line/refine.py ../i23.expt ../i23.refl scan_varying=true`

**branch**
branch

**main**
main

**Comment by dagewa** [comment]
Re correctness, output logs from the two runs are essentially identical:
Screenshot from 2022-03-10 15-09-48

**Comment by dagewa** [comment]
Yep, something stupid is happening when `scan_varying=auto`. This appears to enter the wrong code path and then not do the calculation sparsely 🤦‍♂️
```
/usr/bin/time -v dials.refine ../i23.expt ../i23.refl log=branch_sv_auto.log
```
```	
        Command being timed: "dials.refine ../i23.expt ../i23.refl log=branch_sv_auto.log"
	User time (seconds): 1312.60
	System time (seconds): 37.22
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 22:30.87
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 19922788
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 48544572
	Voluntary context switches: 112
	Involuntary context switches: 13444
	Swaps: 0
	File system inputs: 0
	File system outputs: 1423248
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

**Comment by dagewa** [comment]
:raised_hands: for code review. I had been testing setting `scan_varying=True` all the time and did not spot that a default `dials.refine` job with a static followed by scan-varying macrocycle did not benefit. Simple fix, and now all is good (I think):
```
	Command being timed: "dials.refine ../i23.expt ../i23.refl"
	User time (seconds): 449.05
	System time (seconds): 5.50
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 7:35.15
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 8288348
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 6541580
	Voluntary context switches: 149
	Involuntary context switches: 4470
	Swaps: 0
	File system inputs: 0
	File system outputs: 1423312
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

**Comment by graeme-winter** [comment]
Sounds like a successful review process. I will update and re-run to verify

**Comment by dagewa** [comment]
@graeme-winter Are you still planning to run the branch against one of your test cases, or is my test sufficient?

**Comment by graeme-winter** [comment]
```
	Command being timed: "dials.refine ../indexed.expt ../indexed.refl"
	User time (seconds): 1215.07
	System time (seconds): 9.49
	Percent of CPU this job got: 99%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 20:27.06
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 9025736
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 13874259
	Voluntary context switches: 8701
	Involuntary context switches: 1059
	Swaps: 0
	File system inputs: 888
	File system outputs: 8
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0

```

**Comment by dagewa** [comment]
Thanks for checking! Looks like a reduction in memory usage of over four times and nearly 5 times shorter wallclock time.

Not sure why the "PR macos python38" check is hanging on amber?

**Pull request merged**
