### PR TITLE
Fix 1030: keep goniometers and scans around if provided in input

### PR DESCRIPTION
**Pull request by graeme-winter**
Includes:
 - do not delete things which are provided as input
 - test change to switch back outlier rejection to sauter_poon
N.B. to get original treatment can import images as stills which deletes goniometer and scan from the get go. 

These are cherry-picked from https://github.com/dials/dials/pull/1075

### CODE REVIEW

**Comment by phyy-nx** [comment]
Hi, don't merge this yet, if that's ok.  I need to think about it.

**Comment by graeme-winter** [comment]
Sure, though if you have a timescale for taking a look I’d appreciate it 🙂👍

**Comment by phyy-nx** [comment]
I've had my think.  Ok to merge.  I can't think of a use case that is broken from my previous post:
https://github.com/dials/dials/issues/1030#issuecomment-557721604

I still would like to see a grid scan and its associated headers so I could look a the resultant imported .json file.

**Comment by graeme-winter** [comment]
Thanks @phyy-nx yes we should add some "proper" grid data to the test set for this, probably via zenodo.

**Pull request merged**
