### PR TITLE
Msgpack update may 2019

### LINKED ISSUE #770: Can't read large msgpack file - memory error
Integrated reflection file for high resolution proteinase K dataset, 5.7m reflections:
- reading integrated pickle file succeeds
- writing mpack file succeeds (after 35749d4a0671acfdcc4ba2b91c244c5472a621b6)
- reading mpack file consumes all available memory and eventually the process is killed
```
$ dials.python -c 'from dials.array_family import flex; refl = flex.reflection_table.from_pickle("/dls/i03/data/2019/cm23003-2/processed/proteinasek/protk_1/protk_1_1_/xia2-dials/DataFiles/AUTOMATIC_DEFAULT_SAD_SWEEP1_reflections.pickle"); print(refl.size()); refl.as_msgpack_file("tmp.pickle"); refl2 = flex.reflection_table.from_msgpack_file("tmp.pickle")'
5707387
Killed
```

### PR DESCRIPTION
**Pull request by jmp1985**
I've modified some aspects of the serialization with msgpack to fix #770.

One change is to the serialization of shoeboxes. Previously most arrays were stored as binary blobs but shoebox arrays were stored like:

```
[
  [ 
    panel, 
    x0, 
    x1, 
    y0, 
    y1, 
    z0, 
    z1,
    [ DATA BINARY BLOB ],
    [ MASK BINARY BLOB ],
    [ BACKGROUND BINARY BLOB ]
  ]
 ...
]
```

The new changes are that shoebox array is now saved as a single binary blob within which is encoded the shoeboxes which can be of varying sizes. This required a small amount of extra code to extract the shoebox structure from the binary data.

A rough bench marking was done with the results as follows:

**Writing pickle file**
 Time taken: 15.182340 seconds

**Writing pickle file no shoebox**
 Time taken: 8.819266 seconds

**Reading pickle file**
 Time taken: 8.765193 seconds
 Memory usage: 7.808916 GB

**Reading pickle file no shoebox**
 Time taken: 6.142642 seconds
 Memory usage: 4.648244 GB

**Writing msgpack file**
 Time taken: 7.144568 seconds

**Writing msgpack file no shoebox**
 Time taken: 6.163091 seconds

**Reading msgpack file**
 Time taken: 4.344059 seconds
 Memory usage: 6.083944 GB

**Reading msgpack file no shoebox**
 Time taken: 2.618643 seconds
 Memory usage: 4.788136 GB

Reading with msgpack is now a lot better. It uses much less memory than before and is similar to the memory usage with pickle. Read and write times are faster than with pickle.

The files on disk have the following sizes. The msgpack files are marginally larger than the pickle files.

```
-rw-r--r-- 1 upc86896 2.1G May 15 10:03 tmp.pickle
-rw-r--r-- 1 upc86896 2.4G May 15 10:04 tmp.mpack
-rw-r--r-- 1 upc86896 1.9G May 15 10:04 tmp_no_shoebox.pickle
-rw-r--r-- 1 upc86896 2.1G May 15 10:04 tmp_no_shoebox.mpack

```

### CODE REVIEW

**Comment by graeme-winter** [comment]
@jmp1985 since msgpack not default file format for output how do I switch on, or will be default within the branch?

**Comment by jmp1985** [comment]
@graeme-winter I will need to merge the changes from the previous msgpack as default branch to make it default. I can either do that in this pull request or make a new msgpack as default pull request.

**Comment by graeme-winter** [comment]
Alternative: I change output format how?

**Comment by jmp1985** [comment]
@graeme-winter unfortunately, this is not currently possible without modifying code because my previous changes were all completely reverted. However, you can change lines saying "as_pickle" to "as_msgpack_file" if you want to try it out manually.

**Comment by Anthchirp** [comment]
```
if os.getenv("DIALS_USE_MESSAGEPACK"):
  .as_msgpack_file
else:
  .as_pickle
```
?

**Comment by graeme-winter** [comment]
works for me 🙂 👍

**Comment by jmp1985** [comment]
@graeme-winter You can now use message pack as default by setting 

`export DIALS_USE_MESSAGEPACK=1`

as suggested by @Anthchirp

**Comment by graeme-winter** [comment]
@jmp1985 dials.index != happy camper:

```
--------------------------------------------------
| Imageset | # indexed | # unindexed | % indexed |
--------------------------------------------------
| 0        | 30491     | 307         | 99.0%     |
--------------------------------------------------
Saving refined experiments to indexed_experiments.json
Saving refined reflections to indexed.pickle
Traceback (most recent call last):
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/index.py", line 203, in <module>
    run()
  File "/Users/graeme/svn/cctbx/build/../modules/dials/command_line/index.py", line 186, in run
    idxr.export_reflections(reflections, file_name=params.output.reflections)
  File "/Users/graeme/svn/cctbx/modules/dials/algorithms/indexing/indexer.py", line 1912, in export_reflections
    reflections.as_file(file_name)
  File "/Users/graeme/svn/cctbx/modules/dials/array_family/flex.py", line 283, in as_file
    self.as_msgpack_file(filename)
  File "/Users/graeme/svn/cctbx/modules/dials/array_family/flex.py", line 238, in as_msgpack_file
    outfile.write(self.as_msgpack())
RuntimeError: dials Internal Error: /Users/graeme/svn/cctbx/modules/dials/array_family/reflection_table_msgpack_adapter.h(227): DIALS_ASSERT(it->is_consistent()) failure.
```

spot finding to mpack was fine, was input

**Comment by jmp1985** [comment]
@graeme-winter Ahhh, perhaps I should be less strict in checking the shoebox data. That check ensures that if the shoebox has data then the dimensions should be consistent with the bounding box data.

**Comment by jmp1985** [comment]
@graeme-winter Actually, the real problem was that my code had a bug.... I had set the dimensions as (x,y,z) rather than (z,y,x)... this is now fixed and I've added an additional check to ensure it's consistent when we read!

**Comment by graeme-winter** [comment]
@jmp1985 fixed thanks - will keep going now

**Comment by graeme-winter** [comment]
Will pick up the review again, sorry fell by wayside

**Comment by graeme-winter** [comment]
Assigned @jmp1985 as merge conflicts would probably be good to resolve before I revisit the back-to-back comparison

**Comment by jmp1985** [comment]
@graeme-winter I have merged master back into this branch so it should be good to test (and hopefully merge once you are satisfied that it works as expected).

**Comment by graeme-winter** [comment]
Reviewing now...

I note that the .refl and .expt changes have not been merged across which probably gives rise to several of these conflicts mentioned above. Hopefully these will not be too painful to merge.

0-th order test:

```
dials.import /Users/graeme/data/i04-eiger-small/Therm_6_2_master.h5 
dials.find_spots imported_experiments.json nproc=8
dials.index imported_experiments.json strong.pickle 
dials.refine_bravais_settings indexed*
dials.refine indexed* scan_varying=1
dials.integrate refined* nproc=8
dials.symmetry integrated*
dials.scale reindexed_*
```

with and without `DIALS_USE_MESSAGEPACK=1` to verify that all works correctly, then next step is to assess file size / storage cost and performance. 

 - Stage 1: does it work? Yes
 - Stage 2: does it give the same answer? Yes - diff of log files only differs by run times / mem usage
 - Stage 3: performance:

```
Pooter says for pickles:

real	9m39.123s
user	31m32.584s
sys	17m27.577s

… and for msg pack:

real	9m50.404s
user	31m20.260s
sys	17m22.876s
```

I call these the same

 - Stage 4: file size - a bit bigger but not offensively so:

```
Grey-Area msgpack :) $ du -ach *pickle
 11M	indexed.pickle
181M	integrated.pickle
 11M	refined.pickle
176M	reindexed_reflections.pickle
199M	scaled.pickle
6.6M	strong.pickle
585M	total
Grey-Area msgpack :) $ du -ach ../pickle/*pickle
 11M	../pickle/indexed.pickle
152M	../pickle/integrated.pickle
 10M	../pickle/refined.pickle
149M	../pickle/reindexed_reflections.pickle
167M	../pickle/scaled.pickle
4.9M	../pickle/strong.pickle
495M	total
```

=> green light from YT

**Comment by rjgildea** [comment]
@graeme-winter can you confirm if the memory issues with large reflection files referred to in https://github.com/dials/dials/issues/770 are no longer an issue with this latest update? Specifically, running the following command failed when reading back the msgpack file:
```
$ dials.python -c 'from dials.array_family import flex; refl = flex.reflection_table.from_pickle("/dls/i03/data/2019/cm23003-2/processed/proteinasek/protk_1/protk_1_1_/xia2-dials/DataFiles/AUTOMATIC_DEFAULT_SAD_SWEEP1_reflections.pickle"); print(refl.size()); refl.as_msgpack_file("tmp.pickle"); refl2 = flex.reflection_table.from_msgpack_file("tmp.pickle")'
```

**Comment by graeme-winter** [comment]
@rjgildea valid; investigating though currently stuck as cannot update .svn repos

**Comment by graeme-winter** [comment]
@rjgildea 

```
from __future__ import print_function
from dials.array_family import flex
refl = flex.reflection_table.from_pickle("/dls/i03/data/2019/cm23003-2/processed/proteinasek/protk_1/protk_1_1_/xia2-dials/DataFiles/AUTOMATIC_DEFAULT_SAD_SWEEP1_reflections.pickle")
print(refl.size())
refl.as_msgpack_file("tmp.pickle")
del(refl)
refl2 = flex.reflection_table.from_msgpack_file("tmp.pickle")
print(refl2.size())
```

gives:

```
cs04r-sc-com99-01 512 :) $ !dia
dials.python run 
5707387
5707387
```

and

```
cs04r-sc-com99-01 512 :) $ du -hs *pickle
2.4G	tmp.pickle
cs04r-sc-com99-01 512 :) $ du -hs /dls/i03/data/2019/cm23003-2/processed/proteinasek/protk_1/protk_1_1_/xia2-dials/DataFiles/AUTOMATIC_DEFAULT_SAD_SWEEP1_reflections.pickle
2.1G	/dls/i03/data/2019/cm23003-2/processed/proteinasek/protk_1/protk_1_1_/xia2-dials/DataFiles/AUTOMATIC_DEFAULT_SAD_SWEEP1_reflections.pickle
```

so think we good

**Pull request merged**
