### PR TITLE
refactor dials.analyse_output

### PR DESCRIPTION
**Pull request by Anthchirp**
Deduplicate code flagged by LGTM by refactoring pseudo-classes into functions.
Some ancillary campsite tidying.

### CODE REVIEW

**Comment by Anthchirp** [comment]
Validation: `dials.analyse_output integrated.refl` writes exact same files before and after change

**Comment by rjgildea** [comment]
I think `dials.analyse_output` has largely been superceded by `dials.report` and could probably be removed entirely. As far as I can tell there haven't been any serious changes to it (beyond wider API changes/code cleanup) for over two years.

**Comment by Anthchirp** [comment]
Add deprecation notice and remove in 2.1?

**Comment by graeme-winter** [comment]
+1

**Pull request merged**
