### PR TITLE
Proposed fix for #1113

### LINKED ISSUE #1113: dials.export for mtz crashes before integration
Not saying this should attempt to do anything sensible; but should definitely not stack trace (from principle of: User seeing a Stack Trace is _Always_ a Bug)
```
$ dials.export indexed.*
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.dev.1310-g89e7d1e36
The following parameters have been modified:

input {
  experiments = indexed.expt
  reflections = indexed.refl
}

Data appears to be unscaled, setting intensity = profile+sum
Data appears to be unscaled, setting mtz.hklout = 'integrated.mtz'
Traceback (most recent call last):
  File "/Users/nickd/dials/dist3/build/../modules/dials/command_line/export.py", line 474, in <module>
    exporter(params, experiments, reflections)
  File "/Users/nickd/dials/dist3/build/../modules/dials/command_line/export.py", line 239, in export_mtz
    m = export_mtz(reflections[0], experiments, params)
  File "/Users/nickd/dials/dist3/modules/dials/util/export_mtz.py", line 465, in export_mtz
    d_min=params.mtz.d_min,
  File "/Users/nickd/dials/dist3/modules/dials/util/filter_reflections.py", line 113, in filter_reflection_table
    assert "intensity.prf.value" in reflection_table
AssertionError
```

### PR DESCRIPTION
**Pull request by graeme-winter**
Catch the AssertionError, provide a human readable error message following guidelines from https://github.com/dials/dials/issues/729

Fixes #1113.

### CODE REVIEW

**Comment by graeme-winter** [comment]
N.B. trivial PR because I would like to get the bikeshedding out the way and get a conclusion on how one should provide user feedback re: input issues, so that we can add to these mythical guidelines.

**Comment by Anthchirp** [comment]
suggest retaining the original assertion error message in the output

**Comment by graeme-winter** [comment]
@Anthchirp original assertion message is empty 🙄

Otherwise I would have done 🙂

**Comment by rjgildea** [comment]
Shouldn't the code that raises an AssertionError actually raise a KeyError (with a useful error message)? Then the calling code can catch/re-raise a KeyError instead.

**Comment by graeme-winter** [comment]
> Shouldn't the code that raises an AssertionError actually raise a KeyError (with a useful error message)? Then the calling code can catch/re-raise a KeyError instead.

Done 👍

**Comment by graeme-winter** [comment]
```
Grey-Area dials-1117 :( $ dials.export indexed.*
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.dev.1318-g3e95193c2
The following parameters have been modified:

input {
  experiments = indexed.expt
  reflections = indexed.refl
}

Data appears to be unscaled, setting intensity = profile+sum
Data appears to be unscaled, setting mtz.hklout = 'integrated.mtz'
Error: 'intensity.prf.value missing from input'
```

**Comment by ndevenish** [comment]
How do people feel about this?
- Early fails by checking user input
- Functions check and raise `ValueError`
```
$ dials.export indexed.refl indexed.expt
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
DIALS 2.dev.1320-g5e4e33a43
The following parameters have been modified:

input {
  experiments = indexed.expt
  reflections = indexed.refl
}

Data appears to be unscaled, setting intensity = profile+sum
Error: No intensity data in reflections; cannot export un-integrated data to MTZ
```

**Comment by rjgildea** [comment]
Would it be worthwhile having some centralised functions to check that the input reflections are a given type, as these kinds of checks are fairly commonplace? E.g.
`check_indexed_reflections()`
`check_integrated_reflections()`
`check_scaled_reflections()`

**Pull request merged**
