### PR TITLE
Fast masking

### PR DESCRIPTION
**Pull request by dagewa**
Dumb workaround for #1061

Pixels outside the trusted mask on at least 100 images
are considered bad and masked

### CODE REVIEW

**Comment by dagewa** [comment]
Ugh. Even on this branch, the masking calculation takes nearly 8 seconds for 100 cbfs

```
dials.import $(dials.data get -q thaumatin_i04)/*.cbf
dials.find_spots imported.expt
```

Snippet from log with changes to time the calculation
```
   0.1: Start trusted range masks
   7.8: End trusted range masks
```

**Comment by dagewa** [comment]
Changed tactic. Now takes 10 images distributed through the imageset. The `thaumatin_i04` job now takes about 0.5s.

**Comment by graeme-winter** [comment]
@dagewa looking at this now - however may be worth explicitly ensuring that we have odd and even frames (or prime numbered frames?) to look for twinklers?

**Comment by dagewa** [comment]
That's an interesting idea. Perhaps 5 pairs of sequential frames rather than 10 evenly spread? I don't know much about the various classes of dodgy pixels to devise optimal sampling.

**Comment by Anthchirp** [comment]
Am wondering - Is the hot pixel information relevant enough to have it available for spot finding, or would it be permissible to accumulate the information during the spot finding main loop and then use it from indexing onwards?
(This may have been asked before, don't recall)

An implicit side-effect of this strategy is that it would only take the spot-found region of the dataset into account.

**Comment by dagewa** [comment]
dials.generate_mask also runs this code, where spot finding information is not available. However it matters far less if that program is slow.

**Comment by graeme-winter** [comment]
I'm trying to fix up the capricious pixel discovery code today which would probably be a better place to look at mask generation from anyways.

**Pull request merged**
