### PR TITLE
Update the imageset_id column in the output of dials.split_experiments

### LINKED ISSUE #1790: dials.scale imageset wrangling breaks xia2.small_molecule
```
                                             Overall    Low     High
High resolution limit                           0.59    1.59    0.59
Low resolution limit                            8.95    8.95    0.60
Completeness                                   97.9   100.0    64.9
Multiplicity                                   12.5    11.9     1.8
I/sigma                                       300.9   704.3    71.2
Rmerge(I)                                     0.019   0.008   0.050
Rmerge(I+/-)                                  0.018   0.008   0.055
Rmeas(I)                                      0.020   0.009   0.067
Rmeas(I+/-)                                   0.020   0.009   0.076
Rpim(I)                                       0.006   0.003   0.045
Rpim(I+/-)                                    0.008   0.004   0.053
CC half                                       1.000   1.000   0.994
Anomalous completeness                         90.4    90.9    13.8
Anomalous multiplicity                          7.4     8.3     1.5
Anomalous correlation                         0.106  -0.408   0.000
Anomalous slope                               4.271
dF/F                                          0.015
dI/s(dI)                                      2.919
Total observations                             8845     549      42
Total unique                                    709      46      24

Writing html report to /Users/graeme/Projects/Cu2OSe03/DEFAULT/scale/33_scaling.html
Traceback (most recent call last):
  File "/Users/graeme/git/dials/build/../modules/dials/command_line/scale.py", line 258, in <module>
    run()
  File "/Users/graeme/git/dials/conda_base/python.app/Contents/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/Users/graeme/git/dials/build/../modules/dials/command_line/scale.py", line 231, in run
    scaled_experiments, joint_table = run_scaling(params, experiments, reflections)
  File "/Users/graeme/git/dials/build/../modules/dials/command_line/scale.py", line 194, in run_scaling
    experiments, joint_table = algorithm.finish()
  File "/Users/graeme/git/dials/modules/dials/algorithms/scaling/algorithm.py", line 311, in finish
    self.reflections = update_imageset_ids(self.experiments, self.reflections)
  File "/Users/graeme/git/dials/modules/dials/util/multi_dataset_handling.py", line 388, in update_imageset_ids
    assert len(set(table["imageset_id"])) == 1
```

Data from 4 sweeps here 

```
xia2 small_molecule=true absorption_level=high /Volumes/Black/Data/i19-Cu2OSeO3-Zr-edge
```

### PR DESCRIPTION
**Pull request by jbeilstenedmands**
Fixes #1790

This updates the output so that each (expt,refl)-pair has a consistent value for the imageset_id; this number in the reflection table allows indexing into the list of imagesets in the corresponding experimentlist.

Current behaviour:
Splitting a dataset with 3 sweeps from 3 imagesets: split_{0,1,2}.expt, split_{0,1,2}.refl with imageset_ids 0,1,2.
New behaviour
Splitting a dataset with 3 sweeps from 3 imagesets: split_{0,1,2}.expt, split_{0,1,2}.refl with imageset_ids 0,0,0.
Now any (split_{i}.refl, split_{i}.expt)-pair has a consistent imageset_id.

### CODE REVIEW

**Comment by jbeilstenedmands** [comment]
Would be good to see if this, plus the recent 3 changes, is sufficient to fix #1093

**Comment by graeme-winter** [comment]
Testing now

**Comment by graeme-winter** [comment]
@jbeilstenedmands your change set does what I would have hoped -> task now executes correctly

Will review now

**Review by graeme-winter — APPROVED** [review]
Read through the changes - they are slightly obscured because they are already in a book-keeping heavy area of DIALS - but they made by issue go away so probably good. 

A test would be good to add, but I appreciate hard to do with what you have available right now...

**Pull request merged**
