### PR TITLE
Stop Azure when unrenamed newsfragments present

### PR DESCRIPTION
**Pull request by Anthchirp**
This prevents running _2n_ builds in a pull request which are then
immediately superseded because the GitHub Action drops in another _2n_
build jobs.

### CODE REVIEW

**Comment by Anthchirp** [comment]
And when it is renamed:

**Comment by ndevenish** [comment]
At the moment the newsfragment job doesn't run for drafts. Will this cause no tests to be run for draft releases if the contributor has included a blank newsfragment?

**Comment by Anthchirp** [comment]
Correct. Can fix this by 
* calling it a feature,
* telling Azure to always run checks if the PR is a draft, even if an unrenamed fragment is present (silly),
* moving the Newsfragment job to Azure, always running it but not enforcing a file being present if the PR is a draft, **or**
* always running the Newsfragment job, even if the PR is a draft

**Comment by ndevenish** [comment]
Could also split up the checking and renaming parts of the newsfragment action. Don't really want to overcomplicate things too much.

**Comment by Anthchirp** [comment]
Yes, that's number 3 and also my preferred solution

**Comment by ndevenish** [comment]
read as (moving the Newsfragment job to Azure) and (always running it but not enforcing a file being present if the PR is a draft)

doesn't need to be fixed to put this in, anyhow

**Review by ndevenish — APPROVED** [review]

**Pull request merged**
