### PR TITLE
adds option for reduced stills_process logging

### PR DESCRIPTION
**Pull request by dermen**
When running jobs in the terminal, this option suppresses a lot of refinement logging, and provides minimal progress feedback to user.

### CODE REVIEW

**Comment by phyy-nx** [comment]
Awesome, this has been high on my list as well.  Big carbon footprint reduction :)

I'll review soon, but I'm inclined to make this default, maybe with a couple adjustments to current logging calls to bubble up one or two key items.

**Comment by phyy-nx** [comment]
@ndevenish I added handlers for xfel modules so that they could use the logging in dials.  Is ok?  See cctbx/cctbx_project#819. When that is merged, and with my new commits above, on this branch using @dermen's `logging_option=disabled`, `dials.stills_process` is utterly silent :)

**Comment by phyy-nx** [comment]
File sizes for the logs from the 6 image SACLA h5 dataset used by test_stills_process:

- Main: 377K
- This branch, `logging_option=suppressed` (the new default): 75K
- This branch, `logging_option=normal`: 372K (the SauterPoon outlier printouts are now hidden unless `sauter_poon.verbose=True`
- This branch, `logging_option=disabled`: 0K

**Comment by phyy-nx** [comment]
@ndevenish ok to merge?  The xfel handler ok?  Thanks and no hurry :)

**Comment by dermen** [comment]
Any status update here ?

**Review by phyy-nx — APPROVED** [review]

**Comment by phyy-nx** [comment]
Some folks are on leave but I think this is fine. Ima hit the auto-merge button.  Thanks @dermen.

**Pull request merged**
