### PR TITLE
Oversample the FFT in dials.symmetry method=fourier

### PR DESCRIPTION
**Pull request by kmdalton**
This PR uses zero-padding of the direct space measurements to oversample the FFT in `dials.symmetry systematic_absences.method=fourier integrated.{expt,refl}`. This smooths out the Fourier transform and provides more points to condition the null model used to assign a probability to the screw axis. 

This may partially address #2695.

### CODE REVIEW

**Review by dagewa — APPROVED** [review]
This is great, thanks! Now to get the algorithm to _fail_ to find the $2_1$ around $a$ I have to set `significance_level=0.99`

**Comment by dagewa** [comment]
The Fourier method works so much better for this data than the default. Are there reasons to prefer the default method in some circumstances, or should we consider making this the default?

**Comment by kmdalton** [comment]
I think it is worth considering making the fourier method the default. My hesitation is that I have only really validated it on a handful of test cases.

**Comment by dagewa** [comment]
Yes, this is one of the things it would be nice to test with a large number of representative data sets. It would be very useful to define such a sample of diffraction data space for tests like this, or even just to be able to run test jobs as part of autoprocessing at beamlines and wait until enough results are accumulated...

**Comment by kmdalton** [comment]
Yeah, maybe we can ask one of the beamlines at Diamond to test it on some historical data? For what it is worth, I think the Fourier method is the default in recent versions of Pointless (see section A3 of [Evans 2011](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3069743/)). However the version used there has a couple of important differences including a 
 1) more sophisticated model of the null hypothesis and
 2) more sophisticated peak scoring. 

I think it would require a significant refactor to implement the exact algorithm in DIALS, because it requires access to non-axial reflections to form the null model. Currently the screw axis scoring methods only get passed the axial reflections. I propose we first figure out how we're doing with the simple score function I implemented, and put a more extensive refactor on the to-do list.

**Review by jbeilstenedmands — APPROVED** [review]
Thanks Kevin @kmdalton for implementing this, it looks better on the datasets I tested it on 👍 .
Regarding making this the default, I discussed with David and we are keen on this idea but we need to make sure we have robustly tested on a range of datasets from Diamond before I would be comfortable changing over.

**Comment by kmdalton** [comment]
I'm 100% on board with thorough testing before changing the default. I'm going to work on this PR a bit more before merging as well. I'm a little unsatisfied with it still.

**Comment by dagewa** [comment]
@kmdalton did you manage to find time to look at this? I certainly found this branch to be an improvement over the current approach. Would it be reasonable to merge this as-is and post an issue regarding the further work you planned?

**Comment by kmdalton** [comment]
@dagewa, this totally fell off my radar. Let me get back to you on Monday. I recall having some concerns, but I need to refresh my memory.

**Comment by dagewa** [comment]
Ok, no problem!

**Comment by dagewa** [comment]
Thanks @kmdalton!

**Comment by dagewa** [comment]
Ok, looks like we get a couple of test failures. I'll try to look into it soon

**Comment by dagewa** [comment]
Hi @kmdalton these tests fail with the new oversampling method

```
FAILED tests/algorithms/symmetry/absences/test_screw_axes.py::test_screw_axes_example_data[fourier] - assert 0.0 > 0.99
FAILED tests/algorithms/symmetry/absences/test_screw_axes.py::test_not_screw_axes[fourier] - assert 0.9979400892500825 < 0.01
```

If I set the default to `oversample=None` then the tests pass, but at least one fails with any value I tested for `oversample` over a large range. I am not sure what is going on here.

**Comment by dagewa** [comment]
Ah I think it might be as simple as the value of `n` is not updated for the new length of the vector `fourier_space`.  I'm guessing based on the other changes that `n` should actually be `d` here:

https://github.com/dials/dials/blob/05d311fca8bc3df149e88d803d260032f06766f2/src/dials/algorithms/symmetry/absences/screw_axes.py#L190-L191

**Comment by dagewa** [comment]
(if I make that change, then the tests pass)

**Comment by kmdalton** [comment]
I concur that it looks wrong. Let me have a look ...

**Comment by kmdalton** [comment]
I will have a fix shortly. Thanks for looking into this.

**Comment by kmdalton** [comment]
@dagewa, I believe the Fourier screw axis detection is fixed now. Let me double check that I did not break the diagnostic plot.

**Pull request merged**
