### PR TITLE
Cleanup dials/command_line directory

### PR DESCRIPTION
**Pull request by rjgildea**
This pull requests removes (most) untested dials/command_line programs with a `dev.dials.*` dispatcher name set. A parallel pull request will be made in the dials_scratch repository to move these programs to dials_scratch/command_line.

In my opinion if the code is worth having in the main dials repository, then it should:

1. have a test
2. probably not hide behind a `dev.dials.*` (these aren't distributed in the CCP4 version of dials anyway)

See also https://github.com/dials/dials/issues/812 for further discussion of reasons behind this (points from issue duplicated below):
1) Contain excessive amounts of code
    - ~28.2k lines of code (out of a total of 91.4k lines of code for the whole project)
    - where appropriate, code should ideally be moved out of the command_line directory

2) Almost half (57 out of 129) of the programs are hidden behind a "dev.dials" dispatcher
    - unlikely to be used (or tested) externally, e.g. via xia2
    - CCP4 do not distribute dev.dials.* dispatchers anyway
    - most likely one-off test scripts that would be better off moved to another repository, e.g. dials_scratch

3) Pollutes the code coverage statistics:
    - https://codecov.io/gh/dials/dials/tree/master/command_line
    - 72 (out of 129) files with 0% test coverage
    - Overall test code coverage for this directory of 37.27% (compared to 62.89% for the whole project)
    - 10,009 (out of 17,108) lines of untested code
    - lack of tests means the scripts are likely to become stale over time as a result of major refactors such as the recent datablock -> experiments move, pickle -> msgpack, or e.g. the recent indexing refactor.

4) Pollutes the LGTM alerts:
    - https://lgtm.com/projects/g/dials/dials/latest/files/?sort=name&dir=ASC&mode=heatmap
    - 92 alerts for command_line directory (out of a total of 227 for the whole project)
    - risks masking genuine errors in code that is actually used in DIALS

### CODE REVIEW

**Comment by Anthchirp** [comment]
on a lighter note I would suggest removing the files as @DiamondLightSource-build-server so you don't mess up your personal project commit line contribution statistics :wink:

**Comment by rjgildea** [comment]
> ### dev.dials.generate_bias_lookup_table
> is implied to be used to generate source code in
> https://github.com/dials/dials/blob/fbbdbe7fdb5c28874cd0fecd4314ee71fa137ea5/algorithms/image/centroid/bias.h#L22-L23

With the parallel PR in https://github.com/dials/dials_scratch/pull/3 the command dev.dials.generate_bias_lookup_table would still exist if you have dials_scratch configured. Alternatively, if the only purpose of command this is to generate some numbers to copy into some source code, I'm not sure it really warrants a command line dispatcher. Perhaps we could move the code into dials/algorithms/image/centroid i.e. next to the code where the output is used in bias.h?

**Comment by rjgildea** [comment]
> ### dev.dials.plot_centroid_analysis
> is referred to in this phil parameter
> https://github.com/dials/dials/blob/fbbdbe7fdb5c28874cd0fecd4314ee71fa137ea5/algorithms/refinement/parameterisation/configure.py#L109-L115

@dagewa will likely have an opinion here - is this command needed/useful? If so, would it be possible to add a test and move out of the `dev.dials.*` namespace?

**Comment by rjgildea** [comment]
> ### dev.dials.merge_reflection_lists
> has test in
> https://github.com/dials/dials/blob/fbbdbe7fdb5c28874cd0fecd4314ee71fa137ea5/test/command_line/test_merge_reflection_lists.py#L30-L32
> 
> 
> which should either be also removed or the command retained. The same is true for...
> ### dev.dials.sort_reflections
> which has tests in
> 
> https://github.com/dials/dials/blob/fbbdbe7fdb5c28874cd0fecd4314ee71fa137ea5/test/command_line/test_sort_reflections.py#L7-L9
> 
This pull request purposely hasn't touched these files as they appear to have tests. It is probably a separate discussion as to whether these are worth keeping or moving out of the `dev.dials.*` namespace.

**Comment by dagewa** [comment]
> > ### dev.dials.plot_centroid_analysis
> > is referred to in this phil parameter
> > https://github.com/dials/dials/blob/fbbdbe7fdb5c28874cd0fecd4314ee71fa137ea5/algorithms/refinement/parameterisation/configure.py#L109-L115
> 
> @dagewa will likely have an opinion here - is this command needed/useful? If so, would it be possible to add a test and move out of the `dev.dials.*` namespace?

I think this command is really a development tool for #162, on which my work stalled. It'd be fine to move to dials_scratch and remove that bit in the dials.refine phil help string

**Comment by Anthchirp** [comment]
re **dev.dials.generate_bias_lookup_table**:
if the code generates code for the main repository then I think it should also live in the main repository, maybe in a `/contrib/` directory as it does not have to be packaged in the future. Agree that it does not need a dispatcher.

re the last 2: my mistake, all good.

**Comment by rjgildea** [comment]
> re **dev.dials.generate_bias_lookup_table**:
> if the code generates code for the main repository then I think it should also live in the main repository, maybe in a `/contrib/` directory as it does not have to be packaged in the future. Agree that it does not need a dispatcher.

See 9ebcecf8e40ec12a6dae0f1cb6867aaa3d871e8e - it made (some) sense to me to place this code next to the place where its output is used.

**Comment by Anthchirp** [comment]
FYI this conflicts with #822 and #822 should have priority. Similarly stuff should only be copied over to dials_scratch after #822 is merged

**Comment by rjgildea** [comment]
I have synched the output file renaming changes from dials/dials#822 with the files moved over to dials_scratch in https://github.com/dials/dials_scratch/pull/3/commits/36351de4ef509e68d26d4509025fac71dc739b64. Any further objections before I go ahead and (squash 'n') merge?

**Comment by dagewa** [comment]
None from me

**Pull request merged**
