### PR TITLE
Show path in rlv title bar

### PR DESCRIPTION
**Pull request by dagewa**
When comparing `dials.reciprocal_lattice_viewer` windows side by side it could be difficult to keep track of which was which because the title bar just says "Reflection data viewer". This change makes it more similar to the `dials.image_viewer`, by printing a useful path up there (here the path to reflections)

Screenshot from 2021-06-30 16-11-43

### CODE REVIEW

**Comment by dagewa** [comment]
Oops looks like I branched off #1770, so included those changes here too

**Comment by Anthchirp** [comment]
`git rebase --onto master 002dc1835e71a5cbe649551c47361798b35d7fd1 && git push -f`
should now be the correct set of commits?

**Comment by dagewa** [comment]
Looks right. Thanks for untangling.

**Comment by ndevenish** [comment]
The test on previous commit are because it looks like the feature branch was inadvertantly rebased onto `master` instead of `main`. Merged in again.

**Comment by Anthchirp** [comment]
> rebased onto master instead of main

:facepalm: sorry

**Comment by ndevenish** [comment]
It's hard to train out that muscle memory sometimes :)

**Pull request merged**
