### PR TITLE
Use get_context(method=fork) on all platforms

### LINKED ISSUE #2746: dials.find_spots_server crashes on modern MacOS
```
Traceback (most recent call last):
  File "/Applications/dials-v3-21-1/build/../modules/dials/src/dials/command_line/find_spots_server.py", line 379, in <module>
    run()
  File "/Applications/dials-v3-21-1/conda_base/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Applications/dials-v3-21-1/build/../modules/dials/src/dials/command_line/find_spots_server.py", line 369, in run
    multiprocessing.set_start_method("fork")
  File "/Applications/dials-v3-21-1/conda_base/lib/python3.11/multiprocessing/context.py", line 247, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: Please report this error to [dials-support@lists.sourceforge.net](mailto:dials-support@lists.sourceforge.net): context has already been set
```

Assigning to myself to verify

### PR DESCRIPTION
**Pull request by graeme-winter**
Fixes #2746

### CODE REVIEW

**Comment by graeme-winter** [comment]
I think the failures are unrelated 🙄

**Comment by biochem-fan** [comment]
Isn't "fork" unsupported in Windows?

**Comment by graeme-winter** [comment]
> Isn't "fork" unsupported in Windows?

Yes

Maybe I should get the program to exit cleanly on that platform then saying it isn't supported (I can see little use for it there anyway)

**Comment by ndevenish** [comment]
If we're fine to drop windows (probably) we should at least add a .removal newsfragment about it.

In general python has moved away from fork for good reasons, but maybe none of those apply in this specific case.

**Pull request merged**
