### PR TITLE
Regenerate all dispatchers when configuring DIALS

### PR DESCRIPTION
**Pull request by ndevenish**
Upward dependencies in the libtbx ecosystem had the need for forward dependencies, especially `libtbx.run_tests_parallel`. Regenerating all the dispatchers after configuring dials resolves this issue.

Fixes https://github.com/cctbx/cctbx_project/issues/758.

### CODE REVIEW

**Comment by dwpaley** [comment]
Just noting that @phyy-nx found this also affects `libtbx.ipython`

**Comment by phyy-nx** [comment]
Can this be merged?  We keep bumping into this issue.  Thanks.

**Comment by ndevenish** [comment]
Yes, apologies - other things have gotten in the way of PR maintenance. With DIALS 3.10 coming up we need to have a blitz....

**Comment by phyy-nx** [comment]
Thanks!

-Aaron

**Pull request merged**
