### PR TITLE
Allow building against HDF5 1.12

### PR DESCRIPTION
**Pull request by Anthchirp**
HDF5 1.12 has been out for nearly two years (February 2020), so I think we can start looking into running on it and see what breaks.

I welcome comments of caution 😄

### CODE REVIEW

**Comment by graeme-winter** [comment]
This absolutely needs trying out, to find out what the impact is. Will investigate.

**Comment by Anthchirp** [comment]
merging in main, so that investigations would cover current numpy+hdf5 versions

**Comment by ndevenish** [comment]
This will get better testing in the main repo, and in any case the conda-forge package appears to be using HDF5 1.12 already.

**Comment by ndevenish** [comment]
Correction: I had thought this was the dxtbx CI, in which case the merge title would have been correct. I apologies for the somewhat confusing mistake.

**Pull request merged**
