### PR TITLE
Fix shoebox memory usage check

### LINKED ISSUE #1111: Integration crashes calculating memory error message
In certain cases (`nproc>1`?) Integration fails due to not having enough memory, but then crashes before it can print out the memory error message:
```
Traceback (most recent call last):
  File "/usr/local/xtal/ccp4-7.1/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/xtal/ccp4-7.1/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/xtal/ccp4-7.1/lib/py2/site-packages/dials/command_line/integrate.py", line 669, in <module>
    script.run()
  File "/usr/local/xtal/ccp4-7.1/lib/py2/site-packages/dials/command_line/integrate.py", line 350, in run
    reflections = integrator.integrate()
  File "/usr/local/xtal/ccp4-7.1/lib/py2/site-packages/dials/algorithms/integration/integrator.py", line 1239, in integrate
    self.reflections, _, time_info = processor.process()
  File "/usr/local/xtal/ccp4-7.1/lib/py2/site-packages/dials/algorithms/integration/processor.py", line 256, in process
    self.manager.initialize()
  File "/usr/local/xtal/ccp4-7.1/lib/py2/site-packages/dials/algorithms/integration/processor.py", line 603, in initialize
    self.compute_processors()
  File "/usr/local/xtal/ccp4-7.1/lib/py2/site-packages/dials/algorithms/integration/processor.py", line 809, in compute_processors
    xsize, ysize, zsize = _average_shoebox_size(self.reflections)
  File "/usr/local/xtal/ccp4-7.1/lib/py2/site-packages/dials/algorithms/integration/processor.py", line 64, in _average_shoebox_size
    shoebox = reflections["shoebox"]
KeyError: "Please report this error to dials-support@lists.sourceforge.net: Unknown column 'shoebox'"
```

### PR DESCRIPTION
**Pull request by benjaminhwilliams**
Sometimes `dials.algorithms.integration.processor._average_shoebox_size` can be called on a reflection table that has no shoeboxes.  In fact, this is the usual case when `dials.algorithms.integration.processor.Manager.compute_processors` is called during a `dials.integrate` process because the predicted reflections have bboxes but don't yet have shoeboxes.

When the multiplicity is so high that the required shoebox memory exceeds the memory limit, `dials.integrate` should raise a nice `RuntimeError` with a meaningful message.  This code path was broken and is fixed by this PR.

fixes #1111

Co-Authored-By: Markus Gerstel <markus.gerstel@diamond.ac.uk>

### CODE REVIEW

**Comment by benjaminhwilliams** [comment]
This probably needs a more thorough test of `dials.algorithms.integration.processor.Manager.compute_processors` that involves creating a `dials.algorithms.integration.processor.Manager` with spoof parameters and exercising `compute_processors` on some dummy reflections with big enough bboxes and a small enough memory limit to trigger the error.  I haven't yet figured out the structure of `Manager` though.

**Comment by benjaminhwilliams** [comment]
Hmm, OK, it seems there's no easy way to mock up a `dials.algorithms.integration.processor.Manager` such that it is guaranteed always to have a required shoebox memory in excess of the shoebox memory limit.  Since the latter depends on the system memory, as measured with `psutil.virtual_memory().total` and I don't know a clever way of spoofing that to specify a fake 'total memory' value, such a test would always be unstable.

**Comment by dagewa** [comment]
I don't know if this will work across modules etc., but can you monkeypatch like this?
```
Python 3.6.7 | packaged by conda-forge | (default, Nov  6 2019, 16:19:42) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.virtual_memory
<function virtual_memory at 0x7f6f10b60ea0>
>>> psutil.old_virtual_memory = psutil.virtual_memory
>>> def monkeypatch(*args, **kwargs):
...  vm=psutil.old_virtual_memory(*args, **kwargs)
...  print("foo")
...  print(vm)
... 
>>> psutil.virtual_memory = monkeypatch
>>> psutil.virtual_memory()
foo
svmem(total=16689537024, available=13574070272, percent=18.7, used=1785917440, free=9428451328, active=3432992768, inactive=2367508480, buffers=592072704, cached=4883095552, shared=1053036544, slab=548208640)
```

**Comment by benjaminhwilliams** [comment]
@dagewa, I think this has suitable tests now.  Would you mind casting your eye over it again and giving us the :+1:/:-1:?

**Comment by Anthchirp** [comment]
we believe this fixes #1111

**Pull request merged**
