### PR TITLE
Avoid subprocess for Windows tests

### PR DESCRIPTION
**Pull request by dagewa**
Two tests were failing on Windows because subprocess does not resolve `.bat` in the dispatcher name.

1. `test_plot_reflections.py` is converted here to use `procrunner`, which fixes that issue.
2. `test_find_spots_server_client.py` is disabled on Windows, because `dials.find_spots_server` does not work there.

### CODE REVIEW

**Review by Anthchirp — APPROVED** [review]

**Comment by Anthchirp** [comment]
> dials.find_spots_server does not work there.

...why is that?

**Comment by dagewa** [comment]
On an account with Administrator privileges to avoid issues with opening sockets, I still get:
```
c:\Users\fcx32934\sw\cctbx>dials.find_spots_server
Sat Feb 20 11:25:29 2021 Serving 20 processes on port 1701
Traceback (most recent call last):
  File "c:\Users\fcx32934\sw\cctbx\build\..\modules\dials\command_line\find_spots_server.py", line 344, in <module>
    run()
  File "c:\Users\fcx32934\sw\cctbx\conda_base\lib\contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "c:\Users\fcx32934\sw\cctbx\build\..\modules\dials\command_line\find_spots_server.py", line 340, in run
    main(params.nproc, params.port)
  File "c:\Users\fcx32934\sw\cctbx\build\..\modules\dials\command_line\find_spots_server.py", line 318, in main
    proc.start()
  File "c:\Users\fcx32934\sw\cctbx\conda_base\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "c:\Users\fcx32934\sw\cctbx\conda_base\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\Users\fcx32934\sw\cctbx\conda_base\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "c:\Users\fcx32934\sw\cctbx\conda_base\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\Users\fcx32934\sw\cctbx\conda_base\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: Please report this error to dials-support@lists.sourceforge.net: cannot pickle '_thread.lock' object

c:\Users\fcx32934\sw\cctbx>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Users\fcx32934\sw\cctbx\conda_base\lib\multiprocessing\spawn.py", line 107, in spawn_main
    new_handle = reduction.duplicate(pipe_handle,
  File "c:\Users\fcx32934\sw\cctbx\conda_base\lib\multiprocessing\reduction.py", line 79, in duplicate
    return _winapi.DuplicateHandle(
PermissionError: [WinError 5] Access is denied
```

**Comment by dagewa** [comment]
Actually it's exactly the same error on my non-admin account. Looks like the usual Windows multiprocessing issues.

**Comment by Anthchirp** [comment]
ah okay, so it's just exactly the same problem as on MacOS with Python 3.8+

**Pull request merged**
