### PR TITLE
Fix beam.get_s0() errors in image viewer for polychromatic data.

### PR DESCRIPTION
**Pull request by toastisme**
This fixes `dials.image_viewer` failing for polychromatic data due to several calls to `beam.get_s0()`, which `Polychromatic` beams do not have. In each of these cases this is only to calculate angles, and so `beam.get_unit_s0()` gives the same result.

### CODE REVIEW

**Comment by phyy-nx** [comment]
Hello, `get_unit_s0` doesn't seem to give the same result, as I discovered today working with MicroED geometry:

```
from dxtbx.model.detector import DetectorFactory
from dxtbx.model.beam import BeamFactory

detector = DetectorFactory.simple('UNKNOWN', 1000, (28,28), '+x', '-y', (0.014,0.014), (4000,4000))
panel = detector[0]
beam = BeamFactory.simple(0.0251)

print("MicroED")
print("Unit s0", panel.get_resolution_at_pixel(beam.get_unit_s0(), (0,0)))
print("s0", panel.get_resolution_at_pixel(beam.get_s0(), (0,0)))

detector = DetectorFactory.simple('UNKNOWN', 100, (50,50), '+x', '-y', (0.050,0.050), (1000,1000))
panel = detector[0]
beam = BeamFactory.simple(1.2)

print("Xray")
print("Unit s0", panel.get_resolution_at_pixel(beam.get_unit_s0(), (0,0)))
print("s0", panel.get_resolution_at_pixel(beam.get_s0(), (0,0)))
```

Output
```
MicroED
Unit s0 25.2686565554563
s0 0.6342432795419082
Xray
Unit s0 1.6506801238857844
s0 1.9808161486629412
```

Because of this the image image viewer's resolution display is off.  Is it too late to fix this for the current release?  @toastisme @ndevenish 
Thanks!

**Comment by phyy-nx** [comment]
@toastisme would this work for tof?
```
$ git diff slip_viewer/tile_generation.py
diff --git a/src/dials/util/image_viewer/slip_viewer/tile_generation.py b/src/dials/util/image_viewer/slip_viewer/tile_generation.py
index 6850f8f95..e1f0ba029 100644
--- a/src/dials/util/image_viewer/slip_viewer/tile_generation.py
+++ b/src/dials/util/image_viewer/slip_viewer/tile_generation.py
@@ -438,7 +438,10 @@ def get_resolution(self, x, y, readout=None):
         beam = self.raw_image.get_beam()
         if detector is None or beam is None:
             return None
-        beam = beam.get_unit_s0()
+        try:
+            beam = beam.get_s0()
+        except AttributeError:
+            beam = beam.get_unit_s0()

         if readout is None:
             return None
```

**Comment by dagewa** [comment]
Perhaps methods like `get_resolution_at_pixel` should take a `Beam` not merely a vector, so they can validate their data

**Comment by toastisme** [comment]
Sorry this slipped my mind! @phyy-nx the s0 vector is still relevant for Polychromatic case for getting the max resolution, but here I think it makes most sense to take the minimum wavelength. Agree with @dagewa that modifying get_resolution_at_pixel might be the best approach. PR for this [#767](https://github.com/cctbx/dxtbx/pull/767)

**Pull request merged**
