### PR TITLE
Faster numpy-based matching of miller indices

### PR DESCRIPTION
**Pull request by rjgildea**
Replace use of the cctbx `match_miller_indices()` method with a faster numpy-based approach.

1. Pre-calculate a mapping of miller indices to a 1D array (using `np.ravel_multi_index()`)
2. Pre-calculate epsilons
3. For each CC1/2 calculation, identify the matching pairs of indices using `np.intersect1d()`

Using a multi-crystal example with 133 datasets in `P 3 2 1` (i.e. an Rij matrix of size `(12 * 133) ** 2 == 2547216`), this PR improves the time taken to calculated the Rij matrix from 126 seconds to 79 seconds.

### CODE REVIEW

**Comment by benjaminhwilliams** [comment]
Ah, I see this got merged.  I think we intended to fix up the PR description, since a lot had changed since the PR was opened.

**Comment by benjaminhwilliams** [comment]
Sorry, it dropped off my to-do list.

**Comment by ndevenish** [comment]
Is
> ``dials.cosym``: Significantly faster calculation of Rij matrix of pairwise correlation coefficients
Still a reasonable description?

**Comment by benjaminhwilliams** [comment]
Yes, the news fragment still makes sense.  It's just that the commit message doesn't match the diff.

**Pull request merged**
