### PR TITLE
Log the experiment number when indexing multiple experiments

### PR DESCRIPTION
**Pull request by dagewa**
Second attempt at fixing #2450. This time I think it does the right thing.

### CODE REVIEW

**Comment by graeme-winter** [comment]
@dagewa  something funny with the change set - many files touched - does this need to be rebased onto current `main` or similar? Am testing the code now to see whether the behaviour is as hoped

**Comment by graeme-winter** [comment]
```
|          0 |          99 |            24 | 80.5%       |
+------------+-------------+---------------+-------------+
Indexing experiment 3
Using max_cell: 87.1 Angstrom
Setting d_min: 1.70
FFT gridding: (256,256,256)
Number of centroids used: 463
```

OK, this now makes me happy - though a _slight_ improvement would be 

```
Indexing experiment 3 / N
```

If you have a chance. This is still much more useful than what was there before though thank you

**Comment by dagewa** [comment]
> @dagewa something funny with the change set - many files touched - does this need to be rebased onto current `main` or similar? Am testing the code now to see whether the behaviour is as hoped

Could be... in my hands lately GitHub has been cursed. Will try merging `main` in

**Comment by dagewa** [comment]
> ```
> Indexing experiment 3 / N
> ```
> 
> If you have a chance. This is still much more useful than what was there before though thank you

No problem, have done that. A consequence of doing so is that the numerator of the displayed fraction is now a 1-based index, not equal to the experimental `id`. This may be an improvement anyway.

**Comment by phyy-nx** [comment]
Chiming in.  Off by ones plague us so much.  Maybe we could keep the original numbering?

`Indexing experiment 0 of 3 total`
`Indexing experiment 1 of 3 total`
`Indexing experiment 2 of 3 total`

Looks weird, but I use the logs to pull stuff out sometimes and correctness is more important than humanness to me.

(if I had my druthers, I'd change everything back to 0 indexed, including the image viewer... :)

**Comment by dagewa** [comment]
I see your point, but I think seeing the message `Indexing experiment 2 of 3 total` last is going to confuse the user, who might then be looking for another one after that.

We have two pieces of information to transmit here, the `id` and the progress. Perhaps we should just keep them separate?

```
Indexing experiment id 2 (3/3)
```

**Comment by phyy-nx** [comment]
👍-AaronOn Aug 6, 2023, at 5:19 AM, David Waterman ***@***.***> wrote:﻿
I see your point, but I think seeing the message Indexing experiment 2 of 3 total last is going to confuse the user, who might then be looking for another one after that.
We have two pieces of information to transmit here, the id and the progress. Perhaps we should just keep them separate?
Indexing experiment id 2 (3/3)

**Pull request merged**
