### PR TITLE
Viewer widget sizing tweaks

### PR DESCRIPTION
**Pull request by dagewa**
With GTK3 there seem to be some issues with widget sizing and margins. This PR attempts to fix the worst of these issues. I would be interested to see how this looks on other platforms.

1. `dials.image_viewer`

The margins seem larger with GTK3. As a result the settings window filled the height of my screen. I reduced margins from 5 to 3 to make the window more compact. In addition I increased the width of the brightness slider.

imviewer-settings

2. `dials.reciprocal_lattice_viewer`

The `FloatSpin` control default size truncated the text entry box. This is even worse (for whatever reason) on CCP4 9.0's distribution of DIALS (see #2751). I set explicit sizes to get wider boxes.

rlv

This is still far from perfect. In particular the `rlv` controls are now quite wide. The second beam centre `FloatSpin` could go on the line below to improve that. But before doing that I'd be interested to know how this looks for other people.

### CODE REVIEW

**Comment by dagewa** [comment]
The conversation [here](https://discuss.wxpython.org/t/my-personal-crusade-against-gtk-3-spinctrls-size/30506) covers the ugly spin control buttons, probably designed for touchscreens. If we're bothered to change the custom code linked in the discussion might recover GTK2-like controls, which looked prettier.

**Comment by ndevenish** [comment]
This probably doesn't need to sync main, as I don't think any of this code is tested anyhow.

Have you tested this on older machines, or do you think that doesn't matter any more?

**Comment by dagewa** [comment]
I've not tested on any other machine yet. I'm not too bothered about going back to check how it looks with GTK 2, but I would like to check if the changes look ok on Windows and Mac. The first I should be able to check myself.

**Comment by dagewa** [comment]
The image viewer settings window looks quite compact, but acceptable I think on Windows
image

The RLV panel is a bit over-wide, but I think it would be okay if I got the second beam centre control on the line below
image

**Comment by dagewa** [comment]
Yeah, that's better
image

**Comment by dagewa** [comment]
Could someone please check this branch doesn't make the viewers look excessively horrible on Mac? I'm happy that it's an improvement on Linux and Windows.

**Comment by dagewa** [comment]
Would like this in the release, if anybody wants to check Mac?

**Comment by ndevenish** [comment]
image

**Pull request merged**
