### PR TITLE
Set dispersion_extended as default spot-finding algorithm (fixes #752)

### LINKED ISSUE #752: Suboptimal spot-finding parameters can negatively impact integration
In some cases integration results appear to be very sensitive to spot-finding parameters.

An example case is for a germanate dataset from DLS beamline I23.

Raw image:
image

Threshold map with default spot-finding parameters:
image

Threshold map with kernel_size=20,20 sigma_b=10 sigma_s=5:
image

1) Process with default parameters:
```
$ xia2 anomalous=True read_all_image_headers=False image=/dls/i23/data/2019/nr23017-1/20190302/germ_9keV/data_1_0001.cbf
```
2) Process with larger kernel size for spotfinding:
```
$ cat find_spots.phil 
spotfinder {
  filter.max_spot_size=10000
  threshold {
    dispersion {
      kernel_size = 20 20
      sigma_background = 10
      sigma_strong = 5
    }
  }
}
$ xia2 anomalous=True read_all_image_headers=False dials.find_spots.phil_file=find_spots.phil image=/dls/i23/data/2019/nr23017-1/20190302/germ_9keV/data_1_0001.cbf
```

Comparison of the results show markedly improved I/sigI and merging R-factors for the larger kernel size in spotfinding:
i_over_sigma_mean
r_pim

Profile model determined using default spot-finding parameters:
sigma b: 0.042689 degrees
sigma m: 0.076268 degrees

Profile model determined using modified spot-finding parameters:
Modified spot-finding parameters:
sigma b: 0.062064 degrees
sigma m: 0.107637 degrees

### PR DESCRIPTION
**Pull request by rjgildea**

### CODE REVIEW

**Comment by graeme-winter** [comment]
Minded to agree this is a very good idea, and we just have to mop up the outcomes afterwards. 

You going to do the same inside xia2? May as well...

**Comment by rjgildea** [comment]
xia2 doesn't specify a default, so you get whatever the dials.find_spots default is (unless you specifically override it:
https://github.com/xia2/xia2/blob/master/Handlers/Phil.py#L269

**Comment by graeme-winter** [comment]
👍 that makes sense

**Comment by dagewa** [comment]
I agree, good time to move forward on this :+1:

**Pull request merged**
