### PR TITLE
Convert sequences to stills on import: delete scan & gonio to make properly stills

### PR DESCRIPTION
**Pull request by graeme-winter**
If convert_sequences_to_stills then delete the goniometer and scan.

At the moment they are imported as a lot of sequences - see discussion in #1030

### CODE REVIEW

**Comment by graeme-winter** [comment]
For what it's worth the tests pass in DIALS just fine, on my macbook at least

**Comment by graeme-winter** [comment]
@phyy-nx I think this does something you want - if we delete the scan and gonio on import then we're providing the route into the system which guarantees you get the behaviour you expect. If you import as sequences then the gonio and scan should be saved - allowing for the information to be used in the analysis.

**Comment by graeme-winter** [comment]
> Changes look relatively trivial, but I would suggest adding a brief test to cover the new behaviour. Something along the lines of running dials.import on a rotation image with `convert_sequences_to_stills=True`, and then verifying that `experiment.is_still() == True` and `experiments.all_stills() == True` and that `experiment.scan is None` and `experiment.goniometer is None`.

👍

**Comment by graeme-winter** [comment]
@rjgildea given added tests you are happy with the PR as is?

**Comment by phyy-nx** [comment]
Very good.  Thanks for this one.

**Comment by graeme-winter** [comment]
@phyy-nx you are welcome, thanks for the feedback

**Pull request merged**
